// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Authority_Reason_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Authority_Reason_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Title { get; set; }

    [ForeignKey("AUTH_Authority_Reason_ID")]
    [InverseProperty("AUTH_Authority_Reason_Extended")]
    public virtual AUTH_Authority_Reason AUTH_Authority_Reason { get; set; }
}