// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Comunix_Urls
{
    [Key]
    public Guid ID { get; set; }

    [Required]
    public string Url { get; set; }

    public Guid? DefaultLanguage { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    public bool IsDefault { get; set; }

    [ForeignKey("AUTH_Municipality_ID")]
    [InverseProperty("AUTH_Comunix_Urls")]
    public virtual AUTH_Municipality AUTH_Municipality { get; set; }

    [ForeignKey("DefaultLanguage")]
    [InverseProperty("AUTH_Comunix_Urls")]
    public virtual LANG_Languages DefaultLanguageNavigation { get; set; }
}