// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("id", Name = "auth_municipalitydistricts_id_uindex", IsUnique = true)]
public partial class AUTH_MunicipalityDistricts
{
    [Key]
    public Guid id { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    public Guid? AUTH_MunicipalityID { get; set; }

    [StringLength(300)]
    public string TEXT_SystemTextsCode { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }
}