// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Municipal_Users
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public Guid? PasswordResetToken { get; set; }

    public Guid? LastLoginToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLoginTimeStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool LockoutEnabled { get; set; }

    public Guid? Logo_FILE_FileInfo_ID { get; set; }

    public bool ForcePasswordReset { get; set; }

    public Guid? ForcePwResetToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ForcePwResetTokenExpirationData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastForceResetMailSent { get; set; }

    public Guid? ExternalLoginToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExternalLoginDate { get; set; }

    public Guid? OldUserID { get; set; }

    [InverseProperty("AUTH_Municipal_Users")]
    public virtual ICollection<AUTH_Municipal_Users_Authority> AUTH_Municipal_Users_Authority { get; set; } = new List<AUTH_Municipal_Users_Authority>();

    [InverseProperty("AUTH_Municipal_Users")]
    public virtual ICollection<AUTH_Municipal_Users_Logins> AUTH_Municipal_Users_Logins { get; set; } = new List<AUTH_Municipal_Users_Logins>();

    [InverseProperty("AUTH_Municipal_Users")]
    public virtual ICollection<AUTH_Municipal_Users_Roles> AUTH_Municipal_Users_Roles { get; set; } = new List<AUTH_Municipal_Users_Roles>();

    [InverseProperty("AUTH_Municpal_Users")]
    public virtual ICollection<FORM_Definition_Deadlines_Target> FORM_Definition_Deadlines_Target { get; set; } = new List<FORM_Definition_Deadlines_Target>();

    [InverseProperty("AUTH_Municipal_Users")]
    public virtual ICollection<FORM_Definition_Tasks_Responsible> FORM_Definition_Tasks_Responsible { get; set; } = new List<FORM_Definition_Tasks_Responsible>();
}