// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Municipal_Users_Authority
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Authority_ID { get; set; }

    public Guid? AUTH_Municipal_Users_ID { get; set; }

    public bool? EnableNotifications { get; set; }

    [ForeignKey("AUTH_Authority_ID")]
    [InverseProperty("AUTH_Municipal_Users_Authority")]
    public virtual AUTH_Authority AUTH_Authority { get; set; }

    [ForeignKey("AUTH_Municipal_Users_ID")]
    [InverseProperty("AUTH_Municipal_Users_Authority")]
    public virtual AUTH_Municipal_Users AUTH_Municipal_Users { get; set; }
}