// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Roles_MainMenu
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Roles_ID { get; set; }

    public Guid? CONF_MainMenu_ID { get; set; }

    [ForeignKey("AUTH_Roles_ID")]
    [InverseProperty("AUTH_Roles_MainMenu")]
    public virtual AUTH_Roles AUTH_Roles { get; set; }

    [ForeignKey("CONF_MainMenu_ID")]
    [InverseProperty("AUTH_Roles_MainMenu")]
    public virtual CONF_MainMenu CONF_MainMenu { get; set; }
}