// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Municipal_Users_Settings
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipal_Users_ID { get; set; }

    public Guid? LANG_Languages_ID { get; set; }
}