// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Authority_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Authority_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string EMail { get; set; }

    public string PecEmail { get; set; }

    public string Description { get; set; }

    public string DescriptionShort { get; set; }

    public string Address { get; set; }

    public string Room { get; set; }

    [ForeignKey("AUTH_Authority_ID")]
    [InverseProperty("AUTH_Authority_Extended")]
    public virtual AUTH_Authority AUTH_Authority { get; set; }
}