// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Municipality
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(250)]
    public string InternalName { get; set; }

    public string Name_Text_SystemTexts_Code { get; set; }

    public string Prefix_Text_SystemTexts_Code { get; set; }

    [Column(TypeName = "image")]
    public byte[] Logo { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    [StringLength(50)]
    public string PhoneCanteenManagement { get; set; }

    public string Address { get; set; }

    public string Location { get; set; }

    public string Phone { get; set; }

    public string Mail { get; set; }

    public string ReportName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MensaPNPrefix { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string RoomPNPrefix { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string OrgPNPrefix { get; set; }

    public bool? FESR_EFRE_Logo { get; set; }

    public bool ShowOnLanding { get; set; }

    [Column(TypeName = "image")]
    public byte[] PanoramicImage { get; set; }

    [Unicode(false)]
    public string D3ProtocolEmail { get; set; }

    public string Province_Text_SystemTexts_Code { get; set; }

    public string Soc_Twitter { get; set; }

    public string Soc_Facebook { get; set; }

    public string Soc_Youtube { get; set; }

    public string Soc_Telegramm { get; set; }

    public string Soc_Instagram { get; set; }

    public string Soc_Whatsapp { get; set; }

    public string Soc_RSS { get; set; }

    public string Aemterkodex { get; set; }

    public string TaxNumber { get; set; }

    public bool? EU_Logo_Active { get; set; }

    public bool? ShowGreenSupportNumber { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MensaRefundPNPrefix { get; set; }

    public bool HasLadinisch { get; set; }

    public string AmtstafelLinkCode { get; set; }

    public string ThemeColor { get; set; }

    [Column(TypeName = "image")]
    public byte[] LogoSquare { get; set; }

    [InverseProperty("AUTH_Municipality")]
    public virtual ICollection<AUTH_Comunix_Urls> AUTH_Comunix_Urls { get; set; } = new List<AUTH_Comunix_Urls>();

    [InverseProperty("AUTH_Municipality")]
    public virtual ICollection<AUTH_Users> AUTH_Users { get; set; } = new List<AUTH_Users>();

    [InverseProperty("AUTH_Municipality")]
    public virtual ICollection<FORM_Definition> FORM_Definition { get; set; } = new List<FORM_Definition>();

    [InverseProperty("AUTH_Municipality")]
    public virtual ICollection<HOME_Municipality_Images> HOME_Municipality_Images { get; set; } = new List<HOME_Municipality_Images>();

    [InverseProperty("AUTH_Municipality")]
    public virtual ICollection<PAY_PagoPa_Identifier_Municipalities> PAY_PagoPa_Identifier_Municipalities { get; set; } = new List<PAY_PagoPa_Identifier_Municipalities>();

    [InverseProperty("Municipality")]
    public virtual ICollection<ROOM_Rooms> ROOM_Rooms { get; set; } = new List<ROOM_Rooms>();
}