// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class AUTH_Municipality_Footer
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Address { get; set; }

    public string Location { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string PEC { get; set; }

    public string CodiceUnivoco { get; set; }

    public string OpeningHours { get; set; }

    public string Cap { get; set; }
}