// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("ID", Name = "canteen_schoolclass_id_uindex", IsUnique = true)]
public partial class CANTEEN_SchoolClass
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(20)]
    public string Name { get; set; }

    public Guid? SchoolTypeID { get; set; }

    [StringLength(200)]
    public string TEXT_SystemText_Code { get; set; }
}