// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Subscriber_Card_Request
{
    [Key]
    public Guid ID { get; set; }

    public Guid AUTH_User_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [StringLength(50)]
    public string SubscriberTaxNumber { get; set; }

    public Guid? PAY_Transaction_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PayedAt { get; set; }

    [Required]
    public string Place { get; set; }

    [Required]
    public string Address { get; set; }

    [Required]
    public string PLZ { get; set; }

    [Required]
    public string Municipality { get; set; }
}