// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Canteen
{
    [Key]
    public Guid ID { get; set; }

    public string Name { get; set; }

    public Guid? CANTEEN_School_ID { get; set; }

    public long? TotalSpots { get; set; }

    [Column(TypeName = "money")]
    public decimal? PricePerUse { get; set; }

    public string EMail { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Unicode(false)]
    public string PricePerUseWithReduction { get; set; }

    public bool DayMo { get; set; }

    public bool DayTue { get; set; }

    public bool DayWed { get; set; }

    public bool DayThu { get; set; }

    public bool DayFri { get; set; }

    public bool DaySat { get; set; }

    public bool DaySun { get; set; }

    public string AddressInfo { get; set; }

    public bool IsActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastListDate { get; set; }

    public string PosUsername { get; set; }

    public string PosPassword { get; set; }

    public Guid? ExternalCheckInAccessToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExternalAccessTokenExpirationDate { get; set; }

    [InverseProperty("CANTEEN_Canteen")]
    public virtual ICollection<CANTEEN_Canteen_Pos> CANTEEN_Canteen_Pos { get; set; } = new List<CANTEEN_Canteen_Pos>();

    [InverseProperty("CANTEEN_Canteen")]
    public virtual ICollection<CANTEEN_Period> CANTEEN_Period { get; set; } = new List<CANTEEN_Period>();

    [ForeignKey("CANTEEN_School_ID")]
    [InverseProperty("CANTEEN_Canteen")]
    public virtual CANTEEN_School CANTEEN_School { get; set; }

    [InverseProperty("CANTEEN_Canteen")]
    public virtual ICollection<CANTEEN_School_Canteen> CANTEEN_School_Canteen { get; set; } = new List<CANTEEN_School_Canteen>();

    [InverseProperty("CANTEEN_Canteen")]
    public virtual ICollection<CANTEEN_Subscriber> CANTEEN_Subscriber { get; set; } = new List<CANTEEN_Subscriber>();
}