// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("CancelDate", "CANTEEN_Subscriber_Movement_Type_ID", "RemovedDate", "Fee", Name = "IX_CANTEEN_Subscriber_Movements_CancelDate_CANTEEN_Subscriber_Movement_Type_ID")]
public partial class CANTEEN_Subscriber_Movements
{
    [Key]
    public Guid ID { get; set; }

    public Guid? CANTEEN_Subscriber_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [Column(TypeName = "money")]
    public decimal? Fee { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CancelDate { get; set; }

    public Guid? CANTEEN_Subscriber_Movement_Type_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    public Guid? AUTH_User_ID { get; set; }

    public Guid? PaymentTransactionID { get; set; }

    [StringLength(100)]
    public string Info { get; set; }

    public bool? IsManual { get; set; }

    public bool IsMunicipalInput { get; set; }

    public Guid? RefundReferenceID { get; set; }

    public bool Used { get; set; }

    public Guid? CANTEEN_RequestRefundBalancesID { get; set; }

    public bool UsedWhileCanceled { get; set; }

    public bool BalanceToLow { get; set; }

    public bool ManualCheckIn { get; set; }

    public bool NotAttended { get; set; }

    [ForeignKey("CANTEEN_Subscriber_ID")]
    [InverseProperty("CANTEEN_Subscriber_Movements")]
    public virtual CANTEEN_Subscriber CANTEEN_Subscriber { get; set; }

    [ForeignKey("CANTEEN_Subscriber_Movement_Type_ID")]
    [InverseProperty("CANTEEN_Subscriber_Movements")]
    public virtual CANTEEN_Subscriber_Movement_Type CANTEEN_Subscriber_Movement_Type { get; set; }

    [ForeignKey("PaymentTransactionID")]
    [InverseProperty("CANTEEN_Subscriber_Movements")]
    public virtual PAY_Transaction PaymentTransaction { get; set; }
}