// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_RequestRefundBalances_Status_Log
{
    [Key]
    public Guid ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ChangeDate { get; set; }

    public Guid AUTH_Users_ID { get; set; }

    public Guid CANTEEN_RequestRefundBalances_ID { get; set; }

    public Guid CANTEEN_RequestRefundBalances_Status_ID { get; set; }

    [InverseProperty("CANTEEN_RequestRefundBalances_StatusLog")]
    public virtual ICollection<CANTEEN_RequestRefundBalances_Status_Log_Extended> CANTEEN_RequestRefundBalances_Status_Log_Extended { get; set; } = new List<CANTEEN_RequestRefundBalances_Status_Log_Extended>();
}