// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Schoolyear_Base_Informations
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(50)]
    public string SchoolYears { get; set; }

    public int? BeginYear { get; set; }

    public int? EndYear { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Startdate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Enddate { get; set; }
}