// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Period
{
    [Key]
    public Guid ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FromDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ToDate { get; set; }

    public bool Active { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    public Guid? CANTEEN_Canteen_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [StringLength(50)]
    public string PeriodType { get; set; }

    public Guid? ParentID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChangeDate { get; set; }

    [StringLength(200)]
    public string Name { get; set; }

    public bool? IsAllDay { get; set; }

    public Guid? SchoolID { get; set; }

    public Guid? SchoolClassID { get; set; }

    [ForeignKey("CANTEEN_Canteen_ID")]
    [InverseProperty("CANTEEN_Period")]
    public virtual CANTEEN_Canteen CANTEEN_Canteen { get; set; }

    [InverseProperty("CANTEEN_Period")]
    public virtual ICollection<CANTEEN_Subscriber> CANTEEN_Subscriber { get; set; } = new List<CANTEEN_Subscriber>();
}