// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Canteen_ExternalAccessLinkHistory
{
    [Key]
    public Guid ID { get; set; }

    public Guid CANTEEN_Canteen_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    public string ActionSystemTextCode { get; set; }

    public string Link { get; set; }

    public Guid? ExternalAccessToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExternalAccessTokenExpirationTime { get; set; }
}