// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Property
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public long? SortOrder { get; set; }

    public bool IsContainer { get; set; }

    [InverseProperty("CANTEEN_Property")]
    public virtual ICollection<CANTEEN_Property_Extended> CANTEEN_Property_Extended { get; set; } = new List<CANTEEN_Property_Extended>();
}