// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_School
{
    [Key]
    public Guid ID { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? SchoolTypeID { get; set; }

    public bool DayMo { get; set; }

    public bool DayTue { get; set; }

    public bool DayWed { get; set; }

    public bool DayThu { get; set; }

    public bool DayFri { get; set; }

    public bool DaySat { get; set; }

    public bool DaySun { get; set; }

    public string EMail { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastListDate { get; set; }

    public string Street { get; set; }

    public string PLZ { get; set; }

    public string Municipality { get; set; }

    [InverseProperty("CANTEEN_School")]
    public virtual ICollection<CANTEEN_Canteen> CANTEEN_Canteen { get; set; } = new List<CANTEEN_Canteen>();

    [InverseProperty("CANTEEN_School")]
    public virtual ICollection<CANTEEN_School_Canteen> CANTEEN_School_Canteen { get; set; } = new List<CANTEEN_School_Canteen>();

    [InverseProperty("CANTEEN_School")]
    public virtual ICollection<CANTEEN_Subscriber> CANTEEN_Subscriber { get; set; } = new List<CANTEEN_Subscriber>();
}