// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("id", Name = "canteen_schooltype_id_uindex", IsUnique = true)]
public partial class CANTEEN_SchoolType
{
    [Key]
    public Guid id { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(500)]
    public string TEXT_SystemText_Code { get; set; }
}