// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Canteen_Pos
{
    [Key]
    public Guid ID { get; set; }

    public Guid? CANTEEN_Canteen_ID { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [ForeignKey("CANTEEN_Canteen_ID")]
    [InverseProperty("CANTEEN_Canteen_Pos")]
    public virtual CANTEEN_Canteen CANTEEN_Canteen { get; set; }

    [InverseProperty("CANTEEN_Canteen_Pos")]
    public virtual ICollection<CANTEEN_POS_Session> CANTEEN_POS_Session { get; set; } = new List<CANTEEN_POS_Session>();
}