// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_Schoolyear_RegistrationPeriods
{
    [Key]
    public Guid ID { get; set; }

    public Guid? CANTEEN_Schoolyear_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BeginDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    [ForeignKey("CANTEEN_Schoolyear_ID")]
    [InverseProperty("CANTEEN_Schoolyear_RegistrationPeriods")]
    public virtual CANTEEN_Schoolyear CANTEEN_Schoolyear { get; set; }
}