// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_RequestRefundBalances_Status_Log_Extended
{
    [Key]
    public Guid ID { get; set; }

    public string Reason { get; set; }

    public string Title { get; set; }

    public Guid CANTEEN_RequestRefundBalances_StatusLog_ID { get; set; }

    public Guid LANG_Languages_ID { get; set; }

    [ForeignKey("CANTEEN_RequestRefundBalances_StatusLog_ID")]
    [InverseProperty("CANTEEN_RequestRefundBalances_Status_Log_Extended")]
    public virtual CANTEEN_RequestRefundBalances_Status_Log CANTEEN_RequestRefundBalances_StatusLog { get; set; }

    [ForeignKey("LANG_Languages_ID")]
    [InverseProperty("CANTEEN_RequestRefundBalances_Status_Log_Extended")]
    public virtual LANG_Languages LANG_Languages { get; set; }
}