// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_User_Tax_Report
{
    [Key]
    public Guid ID { get; set; }

    public Guid AUTH_User_ID { get; set; }

    public int Year { get; set; }

    public Guid FILE_FileInfo_ID { get; set; }

    public Guid LANG_Language_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreationDate { get; set; }

    [Required]
    [StringLength(50)]
    public string UserTaxNumber { get; set; }
}