// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CANTEEN_School_Canteen
{
    [Key]
    public Guid ID { get; set; }

    public Guid? CANTEEN_School_ID { get; set; }

    public Guid? CANTEEN_Canteen_ID { get; set; }

    [ForeignKey("CANTEEN_Canteen_ID")]
    [InverseProperty("CANTEEN_School_Canteen")]
    public virtual CANTEEN_Canteen CANTEEN_Canteen { get; set; }

    [ForeignKey("CANTEEN_School_ID")]
    [InverseProperty("CANTEEN_School_Canteen")]
    public virtual CANTEEN_School CANTEEN_School { get; set; }
}