// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("ContextElementId", Name = "IX_CHAT_Message")]
public partial class CHAT_Message
{
    [Key]
    public Guid ID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ContextElementId { get; set; }

    [Required]
    [StringLength(50)]
    public string ContextType { get; set; }

    public Guid AUTH_Users_ID { get; set; }

    [Unicode(false)]
    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime SendDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReadDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationSendDate { get; set; }

    public string LinkUrl { get; set; }

    public string LinkFaviconUrl { get; set; }

    public string LinkName { get; set; }

    [InverseProperty("CHAT_Message")]
    public virtual ICollection<CHAT_Message_Document> CHAT_Message_Document { get; set; } = new List<CHAT_Message_Document>();
}