// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CONF_Sign
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string ClientID { get; set; }

    public string ClientSecret { get; set; }

    public string AccessToken { get; set; }

    public string ApiAccessPoint { get; set; }

    public string MunicipalSigningMail { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TokenExpirationDate { get; set; }

    public string RefreshToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RefreshTokenExpirationDate { get; set; }

    public string State { get; set; }
}