// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CONF_PagoPA
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string BaseAddressIT { get; set; }

    public string PortaleID { get; set; }

    public string CodiceUtente { get; set; }

    public string CodiceEnte { get; set; }

    public string DescrizioneEntePortaleEsterno { get; set; }

    public string CodiceEntePortaleEsterno { get; set; }

    public string BaseAddressDE { get; set; }

    public string IV { get; set; }

    public string Key { get; set; }

    public string NumeroOperazione { get; set; }

    public string TipologiaServizio { get; set; }

    public bool? IsTest { get; set; }
}