// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CONF_Enviroment
{
    [Key]
    public Guid ID { get; set; }

    public string ProgrammName { get; set; }

    public bool EnableMailConfirming { get; set; }

    public bool EnablePhoneConfirming { get; set; }

    public bool EnabledRegistration { get; set; }

    public bool EnabledSpid { get; set; }
}