// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CONF_MainMenu
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ParentID { get; set; }

    [StringLength(30)]
    public string Icon { get; set; }

    public string Url { get; set; }

    public string TEXT_SystemTextsCode { get; set; }

    public int SortOrder { get; set; }

    public bool Enabled { get; set; }

    public bool? InDevelopment { get; set; }

    public bool? ShowInNavMenu { get; set; }

    public string HeaderHtml { get; set; }

    public string FooterHtml { get; set; }

    public string Group_TEXT_SysemTexts_Code { get; set; }

    public string GroupUrl { get; set; }

    public string FAIcon { get; set; }

    public Guid? APP_Application_ID { get; set; }

    public string NotificationContext { get; set; }

    [InverseProperty("CONF_MainMenu")]
    public virtual ICollection<AUTH_Roles_MainMenu> AUTH_Roles_MainMenu { get; set; } = new List<AUTH_Roles_MainMenu>();
}