// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class CONT_Contact
{
    [Key]
    public Guid ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string EMail { get; set; }

    public string Phone { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [InverseProperty("CONT_Contact")]
    public virtual ICollection<ROOM_RoomOptions_Contact> ROOM_RoomOptions_Contact { get; set; } = new List<ROOM_RoomOptions_Contact>();

    [InverseProperty("CONT_Contact")]
    public virtual ICollection<ROOM_Rooms_Contact> ROOM_Rooms_Contact { get; set; } = new List<ROOM_Rooms_Contact>();
}