// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class D3_Error_Log
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ProtocolElementId { get; set; }

    [Required]
    [StringLength(256)]
    public string ProtocolElementType { get; set; }

    public string ErrorMessage { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LogDate { get; set; }
}