// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FILE_Download_Log
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DownloadDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DownloadExpirationDate { get; set; }

    public Guid? DownloadToken { get; set; }
}