// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FILE_FileInfo
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(500)]
    public string FileName { get; set; }

    [StringLength(10)]
    public string FileExtension { get; set; }

    [StringLength(350)]
    public string FolderName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeleteDate { get; set; }

    [StringLength(50)]
    public string ProtocollNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ProtocollDate { get; set; }

    public long? Size { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastAccess { get; set; }

    public string AdobeSign_Document_ID { get; set; }

    public string AdobeSign_Agreement_ID { get; set; }

    public bool Signed { get; set; }

    public bool? AgreementCreated { get; set; }

    public bool? AgreementComitted { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SelfSigned { get; set; }

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<CANTEEN_RequestRefundBalances_Resource> CANTEEN_RequestRefundBalances_Resource { get; set; } = new List<CANTEEN_RequestRefundBalances_Resource>();

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<CANTEEN_Ressources_Extended> CANTEEN_Ressources_Extended { get; set; } = new List<CANTEEN_Ressources_Extended>();

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<CHAT_Message_Document> CHAT_Message_Document { get; set; } = new List<CHAT_Message_Document>();

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<FILE_FileStorage> FILE_FileStorage { get; set; } = new List<FILE_FileStorage>();

    [InverseProperty("FILE_Fileinfo")]
    public virtual ICollection<FORM_Definition_Property_Extended> FORM_Definition_Property_Extended { get; set; } = new List<FORM_Definition_Property_Extended>();

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<FORM_Definition_Ressources_Extended> FORM_Definition_Ressources_Extended { get; set; } = new List<FORM_Definition_Ressources_Extended>();

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<ORG_Request_Attachment> ORG_Request_Attachment { get; set; } = new List<ORG_Request_Attachment>();

    [InverseProperty("FILE_FileInfo")]
    public virtual ICollection<ROOM_Ressources_Extended> ROOM_Ressources_Extended { get; set; } = new List<ROOM_Ressources_Extended>();
}