// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Ressources
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public long? SortOrder { get; set; }

    [ForeignKey("FORM_Definition_ID")]
    [InverseProperty("FORM_Definition_Ressources")]
    public virtual FORM_Definition FORM_Definition { get; set; }

    [InverseProperty("FORM_Definition_Ressources")]
    public virtual ICollection<FORM_Definition_Ressources_Extended> FORM_Definition_Ressources_Extended { get; set; } = new List<FORM_Definition_Ressources_Extended>();
}