// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Upload
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public bool Multiupload { get; set; }

    public bool Required { get; set; }

    public string AllowedTypes { get; set; }

    public long? SortOrder { get; set; }

    [ForeignKey("FORM_Definition_ID")]
    [InverseProperty("FORM_Definition_Upload")]
    public virtual FORM_Definition FORM_Definition { get; set; }

    [InverseProperty("FORM_Definition_Upload")]
    public virtual ICollection<FORM_Definition_Upload_Extended> FORM_Definition_Upload_Extended { get; set; } = new List<FORM_Definition_Upload_Extended>();
}