// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Application_Municipal_Field_Data
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Application_ID { get; set; }

    public Guid? FORM_Definition_Municipal_Field_ID { get; set; }

    public string Value { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChangeDate { get; set; }

    public Guid? FORM_Definition_Municipal_Field_Type_ID { get; set; }

    public string DescriptionDE { get; set; }

    public string DescriptionIT { get; set; }

    public long? SortOrder { get; set; }

    [ForeignKey("FORM_Application_ID")]
    [InverseProperty("FORM_Application_Municipal_Field_Data")]
    public virtual FORM_Application FORM_Application { get; set; }
}