// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Category
{
    [Key]
    public Guid ID { get; set; }

    public string TEXT_SystemTexts_Code { get; set; }

    [InverseProperty("FORM_Definition_Category")]
    public virtual ICollection<FORM_Definition> FORM_Definition { get; set; } = new List<FORM_Definition>();
}