// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Application_Deadline_Eskalated
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Application_ID { get; set; }

    public Guid? FORM_Definition_Deadlines_Target_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationDate { get; set; }
}