// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Field
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? FORM_Definition_Fields_Type_ID { get; set; }

    public bool Required { get; set; }

    public long? SortOrder { get; set; }

    public string DatabaseName { get; set; }

    public Guid? FORM_Definition_Fields_SubType_ID { get; set; }

    public Guid? FORM_Definition_Field_Parent_ID { get; set; }

    public long? ColumnPos { get; set; }

    public long? ColumnCount { get; set; }

    public bool? HasBorder { get; set; }

    public string ReferenceValueLimit { get; set; }

    public bool IsAnchor { get; set; }

    public bool ShowOnMunicipalSite { get; set; }

    public bool? CanBeRepeated { get; set; }

    [Column(TypeName = "money")]
    public decimal AdditionalCharge { get; set; }

    public bool HasAdditionalCharge { get; set; }

    public Guid? Ref_Signature_Name { get; set; }

    public Guid? Ref_Signature_Mail { get; set; }

    public bool BolloFree { get; set; }

    public bool? UploadMultiple { get; set; }

    public int? AdditionalChargePagoPaIdentifierId { get; set; }

    public bool? OnlyShowInFormRenderer { get; set; }

    public int? OperatorCalculatedField { get; set; }

    public int? DecimalPlaces { get; set; }

    [ForeignKey("AdditionalChargePagoPaIdentifierId")]
    [InverseProperty("FORM_Definition_Field")]
    public virtual PAY_PagoPa_Identifier AdditionalChargePagoPaIdentifier { get; set; }

    [ForeignKey("FORM_Definition_ID")]
    [InverseProperty("FORM_Definition_Field")]
    public virtual FORM_Definition FORM_Definition { get; set; }

    [InverseProperty("FORM_Definition_Field")]
    public virtual ICollection<FORM_Definition_Field_Extended> FORM_Definition_Field_Extended { get; set; } = new List<FORM_Definition_Field_Extended>();

    [InverseProperty("FORM_Definition_Field")]
    public virtual ICollection<FORM_Definition_Field_Option> FORM_Definition_Field_Option { get; set; } = new List<FORM_Definition_Field_Option>();

    [InverseProperty("FORM_Definition_Field")]
    public virtual ICollection<FORM_Definition_Field_Reference> FORM_Definition_Field_ReferenceFORM_Definition_Field { get; set; } = new List<FORM_Definition_Field_Reference>();

    [InverseProperty("FORM_Definition_Field_Source")]
    public virtual ICollection<FORM_Definition_Field_Reference> FORM_Definition_Field_ReferenceFORM_Definition_Field_Source { get; set; } = new List<FORM_Definition_Field_Reference>();
}