// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Application_Upload_File
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Application_Upload_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [ForeignKey("FORM_Application_Upload_ID")]
    [InverseProperty("FORM_Application_Upload_File")]
    public virtual FORM_Application_Upload FORM_Application_Upload { get; set; }
}