// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Person
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? HOME_Person_ID { get; set; }

    [ForeignKey("FORM_Definition_ID")]
    [InverseProperty("FORM_Definition_Person")]
    public virtual FORM_Definition FORM_Definition { get; set; }

    [ForeignKey("HOME_Person_ID")]
    [InverseProperty("FORM_Definition_Person")]
    public virtual HOME_Person HOME_Person { get; set; }
}