// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Additional_FORM
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? FORM_Definition_Additional_ID { get; set; }
}