// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Field_Type
{
    [Key]
    public Guid ID { get; set; }

    public string Description { get; set; }

    public string AdditionalCSS { get; set; }

    public string TEXT_SystemText_Code { get; set; }

    public string Image { get; set; }

    public long? SortOrder { get; set; }

    public bool? ReadOnly { get; set; }

    public bool IsEditable { get; set; }

    public bool IsContainer { get; set; }

    public bool HasReference { get; set; }

    public bool CanBeReferenced { get; set; }

    public bool CanBeAnchor { get; set; }

    public bool IsFavicon { get; set; }

    public bool IsChangeable { get; set; }

    public bool CanBeShowenonMunicipalSite { get; set; }

    [InverseProperty("FORM_Definition_Field_Type")]
    public virtual ICollection<FORM_Definition_Field_SubType> FORM_Definition_Field_SubType { get; set; } = new List<FORM_Definition_Field_SubType>();
}