// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Authority_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public bool HasSigning { get; set; }

    public bool HasMultiSigning { get; set; }

    public bool HasPayment { get; set; }

    public bool HasChat { get; set; }

    public bool HasTasks { get; set; }

    public bool HasFlexiblePrice { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ApplicationDeadline { get; set; }

    public long? EstimateProcessingTime { get; set; }

    public bool Enabled { get; set; }

    public Guid? REPORT_ID { get; set; }

    public Guid? FORM_Definition_Category_ID { get; set; }

    public bool HasPruefungsvermerk { get; set; }

    public bool OnlyForCompanies { get; set; }

    public bool HasBollo { get; set; }

    public string FormCode { get; set; }

    public long? LegalDeadline { get; set; }

    public bool HasMunicipalSigning { get; set; }

    public Guid? FORM_Defintion_Bollo_Type_ID { get; set; }

    public long? Bollo_Amount { get; set; }

    public bool? HasPriorities { get; set; }

    public bool HasCredit { get; set; }

    public bool ShowPrivacy { get; set; }

    public bool MultipleParallelApplications { get; set; }

    public bool OnlyForMunicipal { get; set; }

    public long? SortOrder { get; set; }

    public bool HasIBAN { get; set; }

    public Guid? FORM_Definition_Template_ID { get; set; }

    public bool? HasTemplate { get; set; }

    public bool? Highlight { get; set; }

    public int? DefaultPagoPaIdentifierId { get; set; }

    public Guid? FORM_Defintion_Type_ID { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsOfflineForm { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastModificationDate { get; set; }

    public bool AllowPrenotation { get; set; }

    [ForeignKey("AUTH_Authority_ID")]
    [InverseProperty("FORM_Definition")]
    public virtual AUTH_Authority AUTH_Authority { get; set; }

    [ForeignKey("AUTH_Municipality_ID")]
    [InverseProperty("FORM_Definition")]
    public virtual AUTH_Municipality AUTH_Municipality { get; set; }

    [ForeignKey("FORM_Definition_Category_ID")]
    [InverseProperty("FORM_Definition")]
    public virtual FORM_Definition_Category FORM_Definition_Category { get; set; }

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Deadlines> FORM_Definition_Deadlines { get; set; } = new List<FORM_Definition_Deadlines>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Event> FORM_Definition_Event { get; set; } = new List<FORM_Definition_Event>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Extended> FORM_Definition_Extended { get; set; } = new List<FORM_Definition_Extended>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Field> FORM_Definition_Field { get; set; } = new List<FORM_Definition_Field>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Municipal_Field> FORM_Definition_Municipal_Field { get; set; } = new List<FORM_Definition_Municipal_Field>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Payment_Position> FORM_Definition_Payment_Position { get; set; } = new List<FORM_Definition_Payment_Position>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Person> FORM_Definition_Person { get; set; } = new List<FORM_Definition_Person>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Property> FORM_Definition_Property { get; set; } = new List<FORM_Definition_Property>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Reminder> FORM_Definition_Reminder { get; set; } = new List<FORM_Definition_Reminder>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Ressources> FORM_Definition_Ressources { get; set; } = new List<FORM_Definition_Ressources>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Signings> FORM_Definition_Signings { get; set; } = new List<FORM_Definition_Signings>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Tasks> FORM_Definition_Tasks { get; set; } = new List<FORM_Definition_Tasks>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Theme> FORM_Definition_Theme { get; set; } = new List<FORM_Definition_Theme>();

    [InverseProperty("FORM_Definition")]
    public virtual ICollection<FORM_Definition_Upload> FORM_Definition_Upload { get; set; } = new List<FORM_Definition_Upload>();
}