// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Deadlines_TimeType
{
    [Key]
    public Guid ID { get; set; }

    public string Text_SystemTexts_Code { get; set; }

    [InverseProperty("FORM_Definition_Deadlines_TimeType")]
    public virtual ICollection<FORM_Definition_Deadlines> FORM_Definition_Deadlines { get; set; } = new List<FORM_Definition_Deadlines>();
}