// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Tasks_Responsible
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_Tasks_ID { get; set; }

    public Guid? AUTH_Municipal_Users_ID { get; set; }

    [ForeignKey("AUTH_Municipal_Users_ID")]
    [InverseProperty("FORM_Definition_Tasks_Responsible")]
    public virtual AUTH_Municipal_Users AUTH_Municipal_Users { get; set; }

    [ForeignKey("FORM_Definition_Tasks_ID")]
    [InverseProperty("FORM_Definition_Tasks_Responsible")]
    public virtual FORM_Definition_Tasks FORM_Definition_Tasks { get; set; }
}