// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Template_Signfields
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_Template_ID { get; set; }

    public string FirstnameFieldName { get; set; }

    public string LastnameFieldName { get; set; }

    public string EmailFieldName { get; set; }

    [StringLength(20)]
    public string XPosition { get; set; }

    [StringLength(20)]
    public string YPosition { get; set; }

    [StringLength(20)]
    public string Width { get; set; }

    [StringLength(20)]
    public string Height { get; set; }

    [StringLength(20)]
    public string PageNumber { get; set; }

    public bool SelfSign { get; set; }
}