// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Field_Reference
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_Field_ID { get; set; }

    public Guid? FORM_Definition_Field_Source_ID { get; set; }

    public string TriggerValue { get; set; }

    public bool IsCalculatingFieldReference { get; set; }

    public long? SortOrder { get; set; }

    public bool Negate { get; set; }

    [ForeignKey("FORM_Definition_Field_ID")]
    [InverseProperty("FORM_Definition_Field_ReferenceFORM_Definition_Field")]
    public virtual FORM_Definition_Field FORM_Definition_Field { get; set; }

    [ForeignKey("FORM_Definition_Field_Source_ID")]
    [InverseProperty("FORM_Definition_Field_ReferenceFORM_Definition_Field_Source")]
    public virtual FORM_Definition_Field FORM_Definition_Field_Source { get; set; }
}