// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Field_SubType
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_Field_Type_ID { get; set; }

    public string Regex { get; set; }

    public string HTMLTypeValue { get; set; }

    public string TEXT_SystemTEXT_Code { get; set; }

    [ForeignKey("FORM_Definition_Field_Type_ID")]
    [InverseProperty("FORM_Definition_Field_SubType")]
    public virtual FORM_Definition_Field_Type FORM_Definition_Field_Type { get; set; }
}