// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Application_Status_Municipal
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Application_Status_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public long? SortOrder { get; set; }

    public bool? Enabled { get; set; }

    public bool GeneratesPDF { get; set; }
}