// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Application_Chat
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Application_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SendDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReadDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationSendDate { get; set; }

    public string HyperlinkPastedUrl { get; set; }

    public string HyperlinkFaviconUrl { get; set; }

    public string HyperlinkLinkName { get; set; }

    [ForeignKey("FORM_Application_ID")]
    [InverseProperty("FORM_Application_Chat")]
    public virtual FORM_Application FORM_Application { get; set; }

    [InverseProperty("FORM_Application_Chat")]
    public virtual ICollection<FORM_Application_Chat_Dokument> FORM_Application_Chat_Dokument { get; set; } = new List<FORM_Application_Chat_Dokument>();
}