// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Deadlines
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public long? AdditionalDays { get; set; }

    public Guid? FORM_Definition_Deadlines_TimeType_ID { get; set; }

    [ForeignKey("FORM_Definition_ID")]
    [InverseProperty("FORM_Definition_Deadlines")]
    public virtual FORM_Definition FORM_Definition { get; set; }

    [InverseProperty("FORM_Definition_Deadline")]
    public virtual ICollection<FORM_Definition_Deadlines_Target> FORM_Definition_Deadlines_Target { get; set; } = new List<FORM_Definition_Deadlines_Target>();

    [ForeignKey("FORM_Definition_Deadlines_TimeType_ID")]
    [InverseProperty("FORM_Definition_Deadlines")]
    public virtual FORM_Definition_Deadlines_TimeType FORM_Definition_Deadlines_TimeType { get; set; }
}