// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Application_Status
{
    [Key]
    public Guid ID { get; set; }

    public string TEXT_SystemTexts_Code { get; set; }

    public string Icon { get; set; }

    public bool? Selectable { get; set; }

    public long? SortOrder { get; set; }

    public string Description { get; set; }

    public bool UserSelectable { get; set; }

    public bool? FinishedStatus { get; set; }

    public bool GeneratesPDF { get; set; }

    public bool? IsFinalStatus { get; set; }
}