// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class FORM_Definition_Field_Option
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FORM_Definition_Field_ID { get; set; }

    public long? SortOrder { get; set; }

    [Column(TypeName = "money")]
    public decimal AdditionalCharge { get; set; }

    public bool BolloFree { get; set; }

    public int? AdditionalChargePagoPaIdentifierId { get; set; }

    [ForeignKey("AdditionalChargePagoPaIdentifierId")]
    [InverseProperty("FORM_Definition_Field_Option")]
    public virtual PAY_PagoPa_Identifier AdditionalChargePagoPaIdentifier { get; set; }

    [ForeignKey("FORM_Definition_Field_ID")]
    [InverseProperty("FORM_Definition_Field_Option")]
    public virtual FORM_Definition_Field FORM_Definition_Field { get; set; }

    [InverseProperty("FORM_Definition_Field_Option")]
    public virtual ICollection<FORM_Definition_Field_Option_Extended> FORM_Definition_Field_Option_Extended { get; set; } = new List<FORM_Definition_Field_Option_Extended>();
}