// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Appointment_Kategorie
{
    [Key]
    public Guid ID { get; set; }

    public string TEXT_SystemText_Code { get; set; }

    public string DescriptionText_SystemText_Code { get; set; }

    public Guid? HOME_Appointment_Type_ID { get; set; }
}