// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Location_Document
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Location_ID { get; set; }

    public Guid? HOME_Document_ID { get; set; }

    [ForeignKey("HOME_Document_ID")]
    [InverseProperty("HOME_Location_Document")]
    public virtual HOME_Document HOME_Document { get; set; }

    [ForeignKey("HOME_Location_ID")]
    [InverseProperty("HOME_Location_Document")]
    public virtual HOME_Location HOME_Location { get; set; }
}