// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Location
{
    [Key]
    public Guid ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public Guid? Managed_Home_Person_ID { get; set; }

    public bool Highlight { get; set; }

    public Guid? HOME_Location_Type_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? FILE_FileImage_ID { get; set; }

    public double? Lat { get; set; }

    public double? Lang { get; set; }

    [InverseProperty("HOME_Location")]
    public virtual ICollection<HOME_Location_Document> HOME_Location_Document { get; set; } = new List<HOME_Location_Document>();

    [InverseProperty("HOME_Location")]
    public virtual ICollection<HOME_Location_Extended> HOME_Location_Extended { get; set; } = new List<HOME_Location_Extended>();

    [InverseProperty("HOME_Location")]
    public virtual ICollection<HOME_Location_Person> HOME_Location_Person { get; set; } = new List<HOME_Location_Person>();

    [InverseProperty("HOME_Location")]
    public virtual ICollection<HOME_Location_Theme> HOME_Location_Theme { get; set; } = new List<HOME_Location_Theme>();
}