// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Association_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Association_ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string EMail { get; set; }

    public string PecEmail { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string DescriptionShort { get; set; }

    public string Website { get; set; }

    public string Adress { get; set; }

    [ForeignKey("HOME_Association_ID")]
    [InverseProperty("HOME_Association_Extended")]
    public virtual HOME_Association HOME_Association { get; set; }
}