// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Municipality_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Municipality_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Description { get; set; }

    public string Name { get; set; }

    public string EMail { get; set; }

    public string PecEMail { get; set; }

    public string Address { get; set; }

    public string Room { get; set; }

    [ForeignKey("HOME_Municipality_ID")]
    [InverseProperty("HOME_Municipality_Extended")]
    public virtual HOME_Municipality HOME_Municipality { get; set; }
}