// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Venue
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public Guid? Managed_HOME_Person_ID { get; set; }

    public Guid? Managed_AUTH_Authority_ID { get; set; }

    public Guid? HOME_Venue_Type_ID { get; set; }

    public bool Highlight { get; set; }

    public string PhoneNr { get; set; }

    public Guid? HOME_Person_ID { get; set; }

    public string PhoneNrMobile { get; set; }

    public double? Lat { get; set; }

    public double? Lang { get; set; }

    [InverseProperty("HOME_Venue")]
    public virtual ICollection<HOME_Venue_Document> HOME_Venue_Document { get; set; } = new List<HOME_Venue_Document>();

    [InverseProperty("HOME_Venue")]
    public virtual ICollection<HOME_Venue_Extended> HOME_Venue_Extended { get; set; } = new List<HOME_Venue_Extended>();

    [InverseProperty("HOME_Venue")]
    public virtual ICollection<HOME_Venue_Person> HOME_Venue_Person { get; set; } = new List<HOME_Venue_Person>();

    [InverseProperty("HOME_Venue")]
    public virtual ICollection<HOME_Venue_Theme> HOME_Venue_Theme { get; set; } = new List<HOME_Venue_Theme>();
}