// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Theme
{
    [Key]
    public Guid ID { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    public Guid? HOME_Theme_Type_ID { get; set; }

    public bool Highlight { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    public Guid? Managed_HOME_Person_ID { get; set; }

    public Guid? Managed_AUTH_Authority_ID { get; set; }

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<AUTH_Authority_Theme> AUTH_Authority_Theme { get; set; } = new List<AUTH_Authority_Theme>();

    [InverseProperty("HOME_THEME")]
    public virtual ICollection<CANTEEN_Theme> CANTEEN_Theme { get; set; } = new List<CANTEEN_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<FORM_Definition_Theme> FORM_Definition_Theme { get; set; } = new List<FORM_Definition_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Appointment_Theme> HOME_Appointment_Theme { get; set; } = new List<HOME_Appointment_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Article_Theme> HOME_Article_Theme { get; set; } = new List<HOME_Article_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Association_Theme> HOME_Association_Theme { get; set; } = new List<HOME_Association_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Document_Theme> HOME_Document_Theme { get; set; } = new List<HOME_Document_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Location_Theme> HOME_Location_Theme { get; set; } = new List<HOME_Location_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Organisation_Theme> HOME_Organisation_Theme { get; set; } = new List<HOME_Organisation_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_PNRR_Theme> HOME_PNRR_Theme { get; set; } = new List<HOME_PNRR_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Theme_Extended> HOME_Theme_Extended { get; set; } = new List<HOME_Theme_Extended>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<HOME_Venue_Theme> HOME_Venue_Theme { get; set; } = new List<HOME_Venue_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<MAIN_Theme> MAIN_Theme { get; set; } = new List<MAIN_Theme>();

    [InverseProperty("HOME_Theme")]
    public virtual ICollection<ROOM_Theme> ROOM_Theme { get; set; } = new List<ROOM_Theme>();
}