// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Privacy_Document
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Privacy_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [ForeignKey("HOME_Privacy_ID")]
    [InverseProperty("HOME_Privacy_Document")]
    public virtual HOME_Privacy HOME_Privacy { get; set; }
}