// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_PNRR_Chapter_Document
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_PNRR_Chapter_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [ForeignKey("HOME_PNRR_Chapter_ID")]
    [InverseProperty("HOME_PNRR_Chapter_Document")]
    public virtual HOME_PNRR_Chapter HOME_PNRR_Chapter { get; set; }

    [InverseProperty("HOME_PNRR_Chapter_Document")]
    public virtual ICollection<HOME_PNRR_Chapter_Document_Extended> HOME_PNRR_Chapter_Document_Extended { get; set; } = new List<HOME_PNRR_Chapter_Document_Extended>();
}