// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_PNRR
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_PNRR_Type_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastModificationDate { get; set; }

    public Guid? ManagedByAuthorithyID { get; set; }

    public int SortOrder { get; set; }

    [InverseProperty("HOME_PNRR")]
    public virtual ICollection<HOME_PNRR_Chapter> HOME_PNRR_Chapter { get; set; } = new List<HOME_PNRR_Chapter>();

    [InverseProperty("HOME_PNRR")]
    public virtual ICollection<HOME_PNRR_Extended> HOME_PNRR_Extended { get; set; } = new List<HOME_PNRR_Extended>();

    [InverseProperty("HOME_PNRR")]
    public virtual ICollection<HOME_PNRR_Theme> HOME_PNRR_Theme { get; set; } = new List<HOME_PNRR_Theme>();
}