// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_PNRR_Chapter
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_PNRR_ID { get; set; }

    public int SortOrder { get; set; }

    [ForeignKey("HOME_PNRR_ID")]
    [InverseProperty("HOME_PNRR_Chapter")]
    public virtual HOME_PNRR HOME_PNRR { get; set; }

    [InverseProperty("HOME_PNRR_Chapter")]
    public virtual ICollection<HOME_PNRR_Chapter_Document> HOME_PNRR_Chapter_Document { get; set; } = new List<HOME_PNRR_Chapter_Document>();

    [InverseProperty("HOME_PNRR_Chapter")]
    public virtual ICollection<HOME_PNRR_Chapter_Extended> HOME_PNRR_Chapter_Extended { get; set; } = new List<HOME_PNRR_Chapter_Extended>();
}