// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Document_Data
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Document_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public byte[] Data { get; set; }

    public string Filename { get; set; }

    public string Fileextension { get; set; }

    [ForeignKey("HOME_Document_ID")]
    [InverseProperty("HOME_Document_Data")]
    public virtual HOME_Document HOME_Document { get; set; }
}