// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Impressum_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Impressum_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    [ForeignKey("HOME_Impressum_ID")]
    [InverseProperty("HOME_Impressum_Extended")]
    public virtual HOME_Impressum HOME_Impressum { get; set; }
}