// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_PNRR_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_PNRR_ID { get; set; }

    public string DescriptionShort { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Title { get; set; }

    public string DescriptionList { get; set; }

    [ForeignKey("HOME_PNRR_ID")]
    [InverseProperty("HOME_PNRR_Extended")]
    public virtual HOME_PNRR HOME_PNRR { get; set; }
}