// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Venue_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Venue_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string DescriptionShort { get; set; }

    public string EMail { get; set; }

    public string PECMail { get; set; }

    public string Address { get; set; }

    public string Room { get; set; }

    public string Website { get; set; }

    [ForeignKey("HOME_Venue_ID")]
    [InverseProperty("HOME_Venue_Extended")]
    public virtual HOME_Venue HOME_Venue { get; set; }
}