// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Organisation
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? HOME_Organisation_Type_ID { get; set; }

    public Guid? Managed_HOME_Person_ID { get; set; }

    public Guid? Managed_AUTH_Authority_ID { get; set; }

    public Guid? HOME_Organisation_ID { get; set; }

    public Guid? HOME_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public bool Highlight { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    public string ContactName { get; set; }

    public string ContactEMail { get; set; }

    public string ContactPhone { get; set; }

    public string ContactPECMail { get; set; }

    [InverseProperty("HOME_Organisation")]
    public virtual ICollection<HOME_Appointment> HOME_Appointment { get; set; } = new List<HOME_Appointment>();

    [InverseProperty("HOME_Organisation")]
    public virtual ICollection<HOME_Organisation_Document> HOME_Organisation_Document { get; set; } = new List<HOME_Organisation_Document>();

    [InverseProperty("HOME_Organisation")]
    public virtual ICollection<HOME_Organisation_Extended> HOME_Organisation_Extended { get; set; } = new List<HOME_Organisation_Extended>();

    [InverseProperty("HOME_Organisation")]
    public virtual ICollection<HOME_Organisation_Person> HOME_Organisation_Person { get; set; } = new List<HOME_Organisation_Person>();

    [InverseProperty("HOME_Organisation")]
    public virtual ICollection<HOME_Organisation_Theme> HOME_Organisation_Theme { get; set; } = new List<HOME_Organisation_Theme>();
}