// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Organisation_Person_Type
{
    [Key]
    public Guid ID { get; set; }

    public string Text_SystemTextCode { get; set; }

    public string GroupText_SystemTextCode { get; set; }

    public int? GroupSortOrderID { get; set; }
}