// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_PNRR_Chapter_Document_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_PNRR_Chapter_Document_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Filename { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [ForeignKey("HOME_PNRR_Chapter_Document_ID")]
    [InverseProperty("HOME_PNRR_Chapter_Document_Extended")]
    public virtual HOME_PNRR_Chapter_Document HOME_PNRR_Chapter_Document { get; set; }
}