// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Thematic_Sites
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    public string Color { get; set; }

    public Guid? HOME_Thematic_Sites_Type_ID { get; set; }

    [InverseProperty("HOME_Thematic_Sites")]
    public virtual ICollection<HOME_Thematic_Sites_Document> HOME_Thematic_Sites_Document { get; set; } = new List<HOME_Thematic_Sites_Document>();

    [InverseProperty("HOME_Thematic_Sites")]
    public virtual ICollection<HOME_Thematic_Sites_Extended> HOME_Thematic_Sites_Extended { get; set; } = new List<HOME_Thematic_Sites_Extended>();
}