// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Accessibility_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Accessibility_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Description { get; set; }

    public string Link { get; set; }

    [ForeignKey("HOME_Accessibility_ID")]
    [InverseProperty("HOME_Accessibility_Extended")]
    public virtual HOME_Accessibility HOME_Accessibility { get; set; }
}