// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Municipality_Images
{
    [Key]
    public Guid ID { get; set; }

    public Guid? FILE_FileImage_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [ForeignKey("AUTH_Municipality_ID")]
    [InverseProperty("HOME_Municipality_Images")]
    public virtual AUTH_Municipality AUTH_Municipality { get; set; }
}