// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Organisation_Person
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Organisation_ID { get; set; }

    public Guid? HOME_Person_ID { get; set; }

    public Guid? HOME_Person_Type_ID { get; set; }

    public int? SortOrder { get; set; }

    [ForeignKey("HOME_Organisation_ID")]
    [InverseProperty("HOME_Organisation_Person")]
    public virtual HOME_Organisation HOME_Organisation { get; set; }

    [ForeignKey("HOME_Person_ID")]
    [InverseProperty("HOME_Organisation_Person")]
    public virtual HOME_Person HOME_Person { get; set; }
}