// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Appointment_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Appointment_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string DescriptionShort { get; set; }

    public string Address { get; set; }

    public string Room { get; set; }

    public string ContactAddress { get; set; }

    [ForeignKey("HOME_Appointment_ID")]
    [InverseProperty("HOME_Appointment_Extended")]
    public virtual HOME_Appointment HOME_Appointment { get; set; }
}