// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Person_Office_Hours
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Person_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TimeFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TimeTo { get; set; }

    public int Weekday { get; set; }

    [ForeignKey("HOME_Person_ID")]
    [InverseProperty("HOME_Person_Office_Hours")]
    public virtual HOME_Person HOME_Person { get; set; }
}