// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Article_Document
{
    [Key]
    public Guid ID { get; set; }

    public Guid? HOME_Article_ID { get; set; }

    public Guid? HOME_Document_ID { get; set; }

    [ForeignKey("HOME_Article_ID")]
    [InverseProperty("HOME_Article_Document")]
    public virtual HOME_Article HOME_Article { get; set; }

    [ForeignKey("HOME_Document_ID")]
    [InverseProperty("HOME_Article_Document")]
    public virtual HOME_Document HOME_Document { get; set; }
}