// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class HOME_Article_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public Guid? HOME_Article_ID { get; set; }

    public string Subject { get; set; }

    public string Content { get; set; }

    public string ShortText { get; set; }

    [ForeignKey("HOME_Article_ID")]
    [InverseProperty("HOME_Article_Extended")]
    public virtual HOME_Article HOME_Article { get; set; }
}