// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class INFO_Message
{
    [Key]
    public Guid id { get; set; }

    public Guid? LinkObjectID { get; set; }

    public Guid? ParentID { get; set; }

    [StringLength(600)]
    public string Title { get; set; }

    [StringLength(5)]
    public string Language { get; set; }

    [StringLength(600)]
    public string Image { get; set; }

    public string PageText { get; set; }

    [StringLength(50)]
    public string Tel { get; set; }

    [StringLength(250)]
    public string Mail { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public Guid? MunicipalityID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    [StringLength(1000)]
    public string ExtUrl { get; set; }

    [StringLength(1000)]
    public string FileUrl { get; set; }

    public string ShortText { get; set; }

    public Guid? LanguageID { get; set; }

    public int? SortOrder { get; set; }

    public string Style { get; set; }

    [StringLength(300)]
    public string SubPageUrl { get; set; }

    public Guid? ExtID { get; set; }

    [StringLength(200)]
    public string ExtIDDescription { get; set; }

    [StringLength(400)]
    public string Type { get; set; }
}