// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class INFO_Template
{
    [Key]
    public Guid id { get; set; }

    [StringLength(600)]
    public string Title { get; set; }

    public string PageText { get; set; }

    public Guid? MunicipalityID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateDate { get; set; }

    public string ShortText { get; set; }

    public Guid? LanguageID { get; set; }

    public int? SortOrder { get; set; }

    [StringLength(150)]
    public string Type { get; set; }

    public Guid? ExternalKey { get; set; }

    [StringLength(300)]
    public string ExternalKeyDescription { get; set; }

    [StringLength(300)]
    public string AreaName { get; set; }

    [StringLength(500)]
    public string FunctionName { get; set; }

    public Guid? TemplateType { get; set; }

    [StringLength(40)]
    public string LanguageShort { get; set; }
}