// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class INFO_Template_Type
{
    [Key]
    public Guid id { get; set; }

    [StringLength(500)]
    public string AreaName { get; set; }

    [StringLength(500)]
    public string FunctionName { get; set; }

    public Guid? ExternalID { get; set; }

    [StringLength(200)]
    public string Description { get; set; }
}