// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class LANG_Languages
{
    [Key]
    public Guid ID { get; set; }

    public string Name { get; set; }

    [StringLength(30)]
    public string Code { get; set; }

    public string NameShort { get; set; }

    public string TEXT_SystemsText_Code { get; set; }

    public int? SortingOrder { get; set; }

    [InverseProperty("DefaultLanguageNavigation")]
    public virtual ICollection<AUTH_Comunix_Urls> AUTH_Comunix_Urls { get; set; } = new List<AUTH_Comunix_Urls>();

    [InverseProperty("LANG_Languages")]
    public virtual ICollection<CANTEEN_RequestRefundBalances_Status_Log_Extended> CANTEEN_RequestRefundBalances_Status_Log_Extended { get; set; } = new List<CANTEEN_RequestRefundBalances_Status_Log_Extended>();
}