// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class MAIN_Detail
{
    [Key]
    public Guid ID { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastModificationDate { get; set; }

    public Guid? Managed_AUTH_Authority_ID { get; set; }

    [InverseProperty("MAIN_Detail")]
    public virtual ICollection<MAIN_Detail_Extended> MAIN_Detail_Extended { get; set; } = new List<MAIN_Detail_Extended>();
}