// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class MAIN_Detail_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? MAIN_Detail_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string ForWhom { get; set; }

    public string HowTo { get; set; }

    public string WhatFor { get; set; }

    public string Result { get; set; }

    public string Description { get; set; }

    [ForeignKey("MAIN_Detail_ID")]
    [InverseProperty("MAIN_Detail_Extended")]
    public virtual MAIN_Detail MAIN_Detail { get; set; }
}