// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class META_PhonePrefix
{
    [Key]
    public int ID { get; set; }

    [StringLength(4)]
    [Unicode(false)]
    public string Code { get; set; }

    public string Name { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public bool? Preferred { get; set; }

    public string Value { get; set; }
}