// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class META_IstatPaesi_IMPORTFROMEXCEL
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(200)]
    public string Continent { get; set; }

    [StringLength(200)]
    public string ContinentAreaName { get; set; }

    [StringLength(200)]
    public string CodeIstat { get; set; }

    [StringLength(200)]
    public string NameIT { get; set; }

    [StringLength(200)]
    public string NameEN { get; set; }

    [StringLength(200)]
    public string CodeMin { get; set; }

    [StringLength(200)]
    public string CodeAT { get; set; }

    [StringLength(200)]
    public string CodeIso2 { get; set; }

    [StringLength(200)]
    public string CodeIso3 { get; set; }
}