// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("ID", Name = "meta_istatcomuni_id_uindex", IsUnique = true)]
public partial class META_IstatComuni
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(250)]
    public string NameDE { get; set; }

    [StringLength(250)]
    public string NameIT { get; set; }

    [StringLength(250)]
    public string Region { get; set; }

    [StringLength(250)]
    public string RegionCity { get; set; }

    [StringLength(50)]
    public string CodeShort { get; set; }

    [StringLength(50)]
    public string CodeCatastale { get; set; }

    [StringLength(50)]
    public string CodeComune { get; set; }

    [StringLength(50)]
    public string Cap { get; set; }
}