// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("id", Name = "msg_messagetype_id_uindex", IsUnique = true)]
public partial class MSG_MessageType
{
    [Key]
    public Guid id { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    [StringLength(500)]
    public string TEXT_SystemText_Code { get; set; }

    public bool? SendPush { get; set; }

    public bool? SendMail { get; set; }

    public bool? SendSms { get; set; }

    public bool? ShowInList { get; set; }

    [InverseProperty("MessageType")]
    public virtual ICollection<MSG_Message> MSG_Message { get; set; } = new List<MSG_Message>();
}