// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class MSG_Mailer
{
    [Key]
    public Guid ID { get; set; }

    public string ToAdress { get; set; }

    public string FromAdress { get; set; }

    public string DisplayName { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PlannedSendDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RealSendDate { get; set; }

    public Guid? MessageID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeleteDate { get; set; }
}