// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class MSG_SystemMessages
{
    [Key]
    public Guid ID { get; set; }

    public Guid MSG_SystemMessageTypesID { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public string Code { get; set; }

    public string Message { get; set; }
}