// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class MSG_Push
{
    [Key]
    public Guid ID { get; set; }

    public string MunicipalityName { get; set; }

    public Guid? UserID { get; set; }

    public string MessageEN { get; set; }

    public string MessageDE { get; set; }

    public string MessageIT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SendDate { get; set; }

    public Guid? MessageID { get; set; }
}