// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class MSG_SMS
{
    [Key]
    public Guid ID { get; set; }

    public string PhoneNumber { get; set; }

    public string DisplayName { get; set; }

    public string Message { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SendDate { get; set; }

    public Guid? MessageID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }
}