// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ORG_Request_Attachment
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ORG_Request_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [ForeignKey("FILE_FileInfo_ID")]
    [InverseProperty("ORG_Request_Attachment")]
    public virtual FILE_FileInfo FILE_FileInfo { get; set; }

    [ForeignKey("ORG_Request_ID")]
    [InverseProperty("ORG_Request_Attachment")]
    public virtual ORG_Request ORG_Request { get; set; }
}