// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ORG_Request_User
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    public Guid? ORG_AUTH_Users_ID { get; set; }

    public Guid? ORG_Request_Status_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StatusChangeDate { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }
}