// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ORG_Request_Status_Log_Extended
{
    [Key]
    public Guid ID { get; set; }

    public string Reason { get; set; }

    public string Title { get; set; }

    public Guid? ORG_Request_Status_Log_ID { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    [ForeignKey("ORG_Request_Status_Log_ID")]
    [InverseProperty("ORG_Request_Status_Log_Extended")]
    public virtual ORG_Request_Status_Log ORG_Request_Status_Log { get; set; }
}