// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ORG_Request_Ressource
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ORG_Request_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public bool? UserUpload { get; set; }

    [ForeignKey("ORG_Request_ID")]
    [InverseProperty("ORG_Request_Ressource")]
    public virtual ORG_Request ORG_Request { get; set; }
}