// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class PAY_PagoPa_Identifier
{
    [Key]
    public int ID { get; set; }

    public string TEXT_SystemText_Code { get; set; }

    public string PagoPA_Identifier { get; set; }

    public bool? IsMensa { get; set; }

    public bool? IsRooms { get; set; }

    public bool? IsApplications { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsBollo { get; set; }

    [Unicode(false)]
    public string TipologiaServizio { get; set; }

    [InverseProperty("AdditionalChargePagoPaIdentifier")]
    public virtual ICollection<FORM_Definition_Field> FORM_Definition_Field { get; set; } = new List<FORM_Definition_Field>();

    [InverseProperty("AdditionalChargePagoPaIdentifier")]
    public virtual ICollection<FORM_Definition_Field_Option> FORM_Definition_Field_Option { get; set; } = new List<FORM_Definition_Field_Option>();

    [InverseProperty("PAY_PagoPa_Identifier")]
    public virtual ICollection<FORM_Definition_Payment_Position> FORM_Definition_Payment_Position { get; set; } = new List<FORM_Definition_Payment_Position>();

    [InverseProperty("PAY_PagoPa_Identifier")]
    public virtual ICollection<PAY_PagoPa_Identifier_Municipalities> PAY_PagoPa_Identifier_Municipalities { get; set; } = new List<PAY_PagoPa_Identifier_Municipalities>();
}