// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class PAY_Transaction
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public Guid? PAY_Type_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    [Column(TypeName = "money")]
    public decimal? TotalAmount { get; set; }

    public bool? PayFeeSet { get; set; }

    public string STRIPE_Session_ID { get; set; }

    public Guid? Family_ID { get; set; }

    public string PagoPANummero { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationSendDate { get; set; }

    public string ComunixSource { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PagoPANotificationDate { get; set; }

    public string PagoPANotificationValue { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentReminderSentDate { get; set; }

    public bool? DisplayInServices { get; set; }

    [InverseProperty("PaymentTransaction")]
    public virtual ICollection<CANTEEN_Subscriber_Movements> CANTEEN_Subscriber_Movements { get; set; } = new List<CANTEEN_Subscriber_Movements>();

    [InverseProperty("PAY_Transaction")]
    public virtual ICollection<FORM_Application_Transactions> FORM_Application_Transactions { get; set; } = new List<FORM_Application_Transactions>();

    [InverseProperty("PAY_Transaction")]
    public virtual ICollection<PAY_Transaction_Position> PAY_Transaction_Position { get; set; } = new List<PAY_Transaction_Position>();

    [InverseProperty("PAY_Transaction")]
    public virtual ICollection<ROOM_BookingTransactions> ROOM_BookingTransactions { get; set; } = new List<ROOM_BookingTransactions>();
}