// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class PAY_Transaction_Position
{
    [Key]
    public Guid ID { get; set; }

    [Column(TypeName = "money")]
    public decimal? Amount { get; set; }

    public string Description { get; set; }

    public long? SortOrder { get; set; }

    public Guid? PAY_Transaction_ID { get; set; }

    public bool IsFee { get; set; }

    public bool IsBollo { get; set; }

    public string BolloNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RefundDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BolloCreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ICPayedAt { get; set; }

    public string BolloHash { get; set; }

    public Guid? BolloFILE_FileInfo_ID { get; set; }

    public long? BolloHashType { get; set; }

    public string PagoPA_Identification { get; set; }

    [Unicode(false)]
    public string TipologiaServizio { get; set; }

    [ForeignKey("PAY_Transaction_ID")]
    [InverseProperty("PAY_Transaction_Position")]
    public virtual PAY_Transaction PAY_Transaction { get; set; }
}