// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class PAY_PagoPa_Identifier_Municipalities
{
    [Key]
    public Guid ID { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    public int PAY_PagoPa_Identifier_ID { get; set; }

    [ForeignKey("AUTH_Municipality_ID")]
    [InverseProperty("PAY_PagoPa_Identifier_Municipalities")]
    public virtual AUTH_Municipality AUTH_Municipality { get; set; }

    [ForeignKey("PAY_PagoPa_Identifier_ID")]
    [InverseProperty("PAY_PagoPa_Identifier_Municipalities")]
    public virtual PAY_PagoPa_Identifier PAY_PagoPa_Identifier { get; set; }
}