// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_RoomOptions_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_RoomOptions_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    [ForeignKey("ROOM_RoomOptions_ID")]
    [InverseProperty("ROOM_RoomOptions_Extended")]
    public virtual ROOM_RoomOptions ROOM_RoomOptions { get; set; }
}