// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_BookingTransactions
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_BookingGroupID { get; set; }

    public Guid? PAY_Transaction_ID { get; set; }

    [ForeignKey("PAY_Transaction_ID")]
    [InverseProperty("ROOM_BookingTransactions")]
    public virtual PAY_Transaction PAY_Transaction { get; set; }

    [ForeignKey("ROOM_BookingGroupID")]
    [InverseProperty("ROOM_BookingTransactions")]
    public virtual ROOM_BookingGroup ROOM_BookingGroup { get; set; }
}