// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_Booking_Ressource
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_BookingGroup_ID { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public bool? UserUpload { get; set; }

    [ForeignKey("ROOM_BookingGroup_ID")]
    [InverseProperty("ROOM_Booking_Ressource")]
    public virtual ROOM_BookingGroup ROOM_BookingGroup { get; set; }
}