// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("ID", Name = "room_roomgalerie_id_uindex", IsUnique = true)]
public partial class ROOM_RoomGalerie
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(500)]
    public string FileName { get; set; }

    [StringLength(50)]
    public string FileType { get; set; }

    public int? Pos { get; set; }

    [StringLength(1000)]
    public string ServerPath { get; set; }

    public Guid? ROOM_Room_ID { get; set; }

    public Guid? FILE_FileInfo { get; set; }

    public string Copyright { get; set; }

    public bool? FirstImage { get; set; }

    [ForeignKey("ROOM_Room_ID")]
    [InverseProperty("ROOM_RoomGalerie")]
    public virtual ROOM_Rooms ROOM_Room { get; set; }
}