// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("ID", Name = "room_bookingstatus_id_uindex", IsUnique = true)]
public partial class ROOM_BookingStatus
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(150)]
    public string StatusName { get; set; }

    [StringLength(350)]
    public string TEXT_SystemTextsCode { get; set; }

    public bool ShowInCalendar { get; set; }

    public string IconCSS { get; set; }

    public bool? GeneratesPDF { get; set; }

    public bool? IsFinalStatus { get; set; }

    public long? SortOrder { get; set; }

    public bool CanBeCancelled { get; set; }

    public bool? UserSelectable { get; set; }
}