// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("id", Name = "room_timetable_id_uindex", IsUnique = true)]
public partial class ROOM_TimeTable
{
    [Key]
    public Guid id { get; set; }

    [StringLength(50)]
    public string TimeString { get; set; }

    public int? HourValue { get; set; }

    public int? MinuteValue { get; set; }

    public int? StartMinuteOfTheDay { get; set; }
}