// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_Rooms_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_Rooms_ID { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string Location { get; set; }

    [ForeignKey("ROOM_Rooms_ID")]
    [InverseProperty("ROOM_Rooms_Extended")]
    public virtual ROOM_Rooms ROOM_Rooms { get; set; }
}