// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_Booking
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_Room_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? ROOM_BookingGroup_ID { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? Price { get; set; }

    public Guid? ROOM_BookingGroupBackend_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    [ForeignKey("ROOM_BookingGroup_ID")]
    [InverseProperty("ROOM_Booking")]
    public virtual ROOM_BookingGroup ROOM_BookingGroup { get; set; }

    [ForeignKey("ROOM_Room_ID")]
    [InverseProperty("ROOM_Booking")]
    public virtual ROOM_Rooms ROOM_Room { get; set; }
}