// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_RoomOptions_Contact
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_RoomOptions_ID { get; set; }

    public Guid? CONT_Contact_ID { get; set; }

    public bool SendEmail { get; set; }

    public bool SendSMS { get; set; }

    [ForeignKey("CONT_Contact_ID")]
    [InverseProperty("ROOM_RoomOptions_Contact")]
    public virtual CONT_Contact CONT_Contact { get; set; }

    [ForeignKey("ROOM_RoomOptions_ID")]
    [InverseProperty("ROOM_RoomOptions_Contact")]
    public virtual ROOM_RoomOptions ROOM_RoomOptions { get; set; }
}