// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_Contact_Type
{
    [Key]
    public Guid ID { get; set; }

    public string TEXT_SystemText_Code { get; set; }

    public long? SortOrder { get; set; }

    [InverseProperty("ROOM_Contact_Type")]
    public virtual ICollection<ROOM_Rooms_Contact_Type> ROOM_Rooms_Contact_Type { get; set; } = new List<ROOM_Rooms_Contact_Type>();
}