// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_Rooms
{
    [Key]
    public Guid ID { get; set; }

    public Guid MunicipalityID { get; set; }

    public int? MaxCapacity { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public int? SurfaceM2 { get; set; }

    public bool Enabled { get; set; }

    public Guid? RoomGroupFamilyID { get; set; }

    [StringLength(50)]
    public string RoomColor { get; set; }

    public bool HasDirectPay { get; set; }

    public bool HasSigning { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public bool HasRooms { get; set; }

    public Guid? PricingType { get; set; }

    public bool HasSeating { get; set; }

    public int? Seating_Concert { get; set; }

    public int? Seating_Theatre { get; set; }

    public int? Seating_Banquet_Round { get; set; }

    public int? Seating_Banquet_Square { get; set; }

    public int? BufferTime { get; set; }

    [InverseProperty("RoomGroupFamily")]
    public virtual ICollection<ROOM_Rooms> InverseRoomGroupFamily { get; set; } = new List<ROOM_Rooms>();

    [ForeignKey("MunicipalityID")]
    [InverseProperty("ROOM_Rooms")]
    public virtual AUTH_Municipality Municipality { get; set; }

    [InverseProperty("ROOM_Room")]
    public virtual ICollection<ROOM_Booking> ROOM_Booking { get; set; } = new List<ROOM_Booking>();

    [InverseProperty("ROOM_Room")]
    public virtual ICollection<ROOM_RoomGalerie> ROOM_RoomGalerie { get; set; } = new List<ROOM_RoomGalerie>();

    [InverseProperty("ROOM_Room")]
    public virtual ICollection<ROOM_RoomOptions> ROOM_RoomOptions { get; set; } = new List<ROOM_RoomOptions>();

    [InverseProperty("ROOM_Rooms")]
    public virtual ICollection<ROOM_RoomPricing> ROOM_RoomPricing { get; set; } = new List<ROOM_RoomPricing>();

    [InverseProperty("ROOM_Rooms")]
    public virtual ICollection<ROOM_Rooms_Contact> ROOM_Rooms_Contact { get; set; } = new List<ROOM_Rooms_Contact>();

    [InverseProperty("ROOM_Rooms")]
    public virtual ICollection<ROOM_Rooms_Extended> ROOM_Rooms_Extended { get; set; } = new List<ROOM_Rooms_Extended>();

    [ForeignKey("RoomGroupFamilyID")]
    [InverseProperty("InverseRoomGroupFamily")]
    public virtual ROOM_Rooms RoomGroupFamily { get; set; }
}