// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class ROOM_Settings_Extended
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ROOM_Settings_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string ForWhom { get; set; }

    public string HowTo { get; set; }

    public string WhatFor { get; set; }

    public string Result { get; set; }

    [ForeignKey("ROOM_Settings_ID")]
    [InverseProperty("ROOM_Settings_Extended")]
    public virtual ROOM_Settings ROOM_Settings { get; set; }
}