// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class SCRAPER_HtmlStructure
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(250)]
    public string Type { get; set; }

    [StringLength(250)]
    public string Name { get; set; }

    public string Value { get; set; }

    public string InnerHtml { get; set; }

    public string OuterHtml { get; set; }

    public Guid? ScraperID { get; set; }

    public Guid? ParentID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public string XPath { get; set; }

    [StringLength(50)]
    public string HtmlID { get; set; }

    public int? Line { get; set; }

    public int? Position { get; set; }

    [StringLength(350)]
    public string ClassName { get; set; }

    [StringLength(250)]
    public string IDName { get; set; }

    [StringLength(2000)]
    public string Link { get; set; }

    [StringLength(2000)]
    public string ImageLink { get; set; }

    public Guid? RowGroup { get; set; }

    public Guid? INFO_PageID { get; set; }

    [StringLength(2000)]
    public string DocLink1 { get; set; }

    [Column(TypeName = "date")]
    public DateTime? InfoDate { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string DetailHtml { get; set; }

    public Guid? MunicipalityID { get; set; }

    [StringLength(5)]
    public string Language { get; set; }

    public Guid? MenuID { get; set; }

    public bool? SendPush { get; set; }

    public string ShortText { get; set; }
}