// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class SCRAPER_Values
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ScrapeElementID { get; set; }

    public string Value { get; set; }

    public string HtmlValue { get; set; }

    [StringLength(250)]
    public string ScanKey { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ParseDate { get; set; }

    public string ParseLink { get; set; }

    public Guid? GroupKey { get; set; }
}