// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class SCRAPER_Scraper
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(500)]
    public string Title { get; set; }

    [StringLength(1500)]
    public string Url { get; set; }

    [StringLength(1500)]
    public string UrlDetail { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastScrape { get; set; }

    public string HtmlCode { get; set; }

    [StringLength(500)]
    public string ScanKey { get; set; }

    public Guid? MunicipalityID { get; set; }

    [StringLength(50)]
    public string Language { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    public int? ElementsFound { get; set; }

    public bool IsActive { get; set; }

    [StringLength(450)]
    public string ListContainer { get; set; }

    [StringLength(450)]
    public string ItemContainer { get; set; }

    [StringLength(450)]
    public string DetailContainer { get; set; }

    [StringLength(250)]
    public string BaseLink { get; set; }

    public int? SortOrder { get; set; }

    public Guid? MenuID { get; set; }

    public bool? SendPush { get; set; }

    public string DetailHeaderText { get; set; }

    public string DetailFooterTxt { get; set; }

    [StringLength(200)]
    public string DetailContainer1 { get; set; }

    [StringLength(200)]
    public string DetailContainer2 { get; set; }
}