// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class SCRAPER_Elements
{
    [Key]
    public Guid ID { get; set; }

    public Guid? ScraperID { get; set; }

    public Guid? ParentID { get; set; }

    [StringLength(350)]
    public string Name { get; set; }

    [StringLength(350)]
    public string HtmlElement { get; set; }

    [StringLength(350)]
    public string BeforeString { get; set; }

    [StringLength(350)]
    public string AfterString { get; set; }

    [StringLength(350)]
    public string Regex { get; set; }

    [StringLength(350)]
    public string Type { get; set; }

    public bool OnDetailPage { get; set; }

    [StringLength(350)]
    public string ClassOrID { get; set; }

    public bool IsContainer { get; set; }

    [StringLength(350)]
    public string ColumnName { get; set; }

    public bool? IsList { get; set; }

    public bool? IsDetail { get; set; }

    public int? SortOrder { get; set; }

    public int? Level { get; set; }
}