// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Index("ID", Name = "sys_auditlog_id_uindex", IsUnique = true)]
public partial class SYS_AuditLog
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [StringLength(50)]
    public string AuditType { get; set; }

    [StringLength(500)]
    public string TableName { get; set; }

    [StringLength(500)]
    public string ColumnName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public string OriginalValue { get; set; }

    public string CurrentValue { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }
}