// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class SYS_Log
{
    [Key]
    public Guid ID { get; set; }

    [StringLength(500)]
    public string LogInfo { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public int? LogLevel { get; set; }

    public string Message { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string Url { get; set; }
}