// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TASK_Task_Responsible
{
    [Key]
    public Guid ID { get; set; }

    public Guid? TASK_Task_ID { get; set; }

    public Guid? AUTH_Municipal_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastSeenDate { get; set; }

    [Unicode(false)]
    public string SortDesc { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationDate { get; set; }
}