// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TASK_Priority_Extended
{
    [Key]
    public Guid ID { get; set; }

    public string Description { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public Guid? TASK_Priority_ID { get; set; }

    [ForeignKey("TASK_Priority_ID")]
    [InverseProperty("TASK_Priority_Extended")]
    public virtual TASK_Priority TASK_Priority { get; set; }
}