// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TASK_Task_Eskalation
{
    [Key]
    public Guid ID { get; set; }

    public Guid? TASK_Task_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PlannedNotificationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RealNotificationDate { get; set; }

    [ForeignKey("TASK_Task_ID")]
    [InverseProperty("TASK_Task_Eskalation")]
    public virtual TASK_Task TASK_Task { get; set; }

    [InverseProperty("TASK_Task_Eskalation")]
    public virtual ICollection<TASK_Task_Eskalation_Responsible> TASK_Task_Eskalation_Responsible { get; set; } = new List<TASK_Task_Eskalation_Responsible>();
}