// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TASK_Task_Eskalation_Responsible
{
    [Key]
    public Guid ID { get; set; }

    public Guid? TASK_Task_Eskalation_ID { get; set; }

    public Guid? AUTH_Municipal_Users_ID { get; set; }

    public string SortDesc { get; set; }

    [ForeignKey("TASK_Task_Eskalation_ID")]
    [InverseProperty("TASK_Task_Eskalation_Responsible")]
    public virtual TASK_Task_Eskalation TASK_Task_Eskalation { get; set; }
}