// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TEXT_Template
{
    [Key]
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? APP_Applications_ID { get; set; }

    public string ExternalContext { get; set; }

    public string ExternalID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public long? SortOrder { get; set; }

    public bool? IsDocument { get; set; }

    [InverseProperty("TEXT_Template")]
    public virtual ICollection<TEXT_Template_Extended> TEXT_Template_Extended { get; set; } = new List<TEXT_Template_Extended>();
}