// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TEXT_Template_Keyword
{
    [Key]
    public Guid ID { get; set; }

    public string ExternalContext { get; set; }

    public string Keyword { get; set; }

    public long? SortOrder { get; set; }

    public Guid? LANG_Languages_ID { get; set; }
}