// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

public partial class TICKET_Tickets
{
    [Key]
    public Guid ID { get; set; }

    public Guid? MunicipalityID { get; set; }

    [StringLength(550)]
    public string Title { get; set; }

    public string Description { get; set; }

    public Guid? UserID { get; set; }

    public Guid? AssignetToUserID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public int? TicketPriorityID { get; set; }

    public int? TicketPriorityIDAgent { get; set; }

    public int? TicketStatusID { get; set; }

    public string Info { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DueDate { get; set; }

    public string Tags { get; set; }

    public Guid? ParentID { get; set; }

    public int? TicketTypeID { get; set; }

    [StringLength(550)]
    public string EmailAdress { get; set; }
}