// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Authority_Statistik
{
    public Guid ID { get; set; }

    public string TEXT_SystemText_Code { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string Name { get; set; }

    public string Icon { get; set; }

    public long? SortOrder { get; set; }

    public string Mail { get; set; }

    public string Telefon { get; set; }

    public bool IsOfficial { get; set; }

    public bool DynamicForms { get; set; }

    public Guid? CONF_MainMenu_ID { get; set; }

    public int? ApplicationOpenCount { get; set; }

    public int? ApplicationInEditCount { get; set; }

    public int? ApplicationFinishedCount { get; set; }

    public int? ApplicationAfterLegalDeadlineCount { get; set; }

    public int? ApplicationAfterEstimatedDeadlineCount { get; set; }

    public int? ApplicationNotComittedCount { get; set; }
}