// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Organizations
{
    public Guid ID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FiscalNumber { get; set; }

    public string Email { get; set; }

    public string CountyOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string DomicileMunicipality { get; set; }

    public string DomicileNation { get; set; }

    public string DomicilePostalCode { get; set; }

    public string DomicileProvince { get; set; }

    public string DomicileStreetAddress { get; set; }

    public string Gender { get; set; }

    public string MobilePhone { get; set; }

    public string RegisteredOffice { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    public string STRIPE_Customer_ID { get; set; }

    public string VatNumber { get; set; }

    public string PECEmail { get; set; }

    public string CodiceDestinatario { get; set; }

    public Guid? AUTH_Company_LegalForm_ID { get; set; }

    public string HandelskammerEintragung { get; set; }

    public Guid? GV_AUTH_Users_ID { get; set; }

    public string Phone { get; set; }

    public string Username { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public string CompanyType { get; set; }

    public string LegalForm { get; set; }

    [Required]
    public string Fullname { get; set; }

    [Required]
    public string SearchText { get; set; }
}