// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Municipal_Users
{
    public Guid ID { get; set; }

    public Guid Language_ID { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public Guid? PasswordResetToken { get; set; }

    public Guid? LastLoginToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLoginTimeStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool LockoutEnabled { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [StringLength(250)]
    public string Municipality { get; set; }

    public string UserRoles { get; set; }

    public int? UserAuthorities { get; set; }

    public bool ForcePasswordReset { get; set; }

    public Guid? ForcePwResetToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ForcePwResetTokenExpirationData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastForceResetMailSent { get; set; }
}