// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Users
{
    public Guid ID { get; set; }

    public Guid? Anagrafic_ID { get; set; }

    public Guid Language_ID { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public string Username { get; set; }

    public string FiscalNumber { get; set; }

    public string CountyOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string DomicileMunicipality { get; set; }

    public string DomicileNation { get; set; }

    public string DomicilePostalCode { get; set; }

    public string DomicileProvince { get; set; }

    public string DomicileStreetAddress { get; set; }

    public string Gender { get; set; }

    public string RegisteredOffice { get; set; }

    public string PECEmail { get; set; }

    public string Email { get; set; }

    public bool? EmailConfirmed { get; set; }

    public string EmailConfirmToken { get; set; }

    public string PasswordHash { get; set; }

    public Guid? PasswordResetToken { get; set; }

    public Guid LastLoginToken { get; set; }

    public string MobilePhone { get; set; }

    [StringLength(50)]
    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public bool LockoutEnabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [StringLength(250)]
    public string Municipality { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastLoginTimeStamp { get; set; }

    public string RegistrationMode { get; set; }

    public string UserRoles { get; set; }

    public bool VeriffConfirmed { get; set; }

    public string PhoneNumberConfirmToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? VeriffStartDate { get; set; }

    public bool IsOrganization { get; set; }

    public bool ForceEmailVerification { get; set; }

    public bool ForcePhoneVerification { get; set; }

    public bool ForcePasswordReset { get; set; }

    public Guid? ForcePwResetToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ForcePwResetTokenExpirationData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastForceResetMailSent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PrivacyAccepted { get; set; }

    public Guid? SelectedMunicipality { get; set; }
}