// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Roles_CONF_Menu
{
    public Guid ID { get; set; }

    public Guid? AUTH_Roles_ID { get; set; }

    public Guid? CONF_MainMenu_ID { get; set; }

    [Required]
    public string RoleName { get; set; }

    public string Url { get; set; }

    public Guid? ParentID { get; set; }

    public string TEXT_SystemTextsCode { get; set; }

    public int SortOrder { get; set; }

    public bool Enabled { get; set; }

    public bool? InDevelopment { get; set; }

    public bool? ShowInNavMenu { get; set; }
}