// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Company_Type
{
    public Guid ID { get; set; }

    public string TEXT_System_Texts_Code { get; set; }

    public bool IsAssociation { get; set; }

    public bool IsPrivate { get; set; }

    public bool IsOnulus { get; set; }

    public bool IsSport { get; set; }

    public bool CanBeRepresentation { get; set; }

    public bool HasLegalForm { get; set; }

    public string Text { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public bool ShowOnRooms { get; set; }

    public bool CanBeBolloFree { get; set; }
}