// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Users_Roles
{
    [StringLength(250)]
    public string InternalName { get; set; }

    [Required]
    public string Role { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    public Guid AUTH_Users_ID { get; set; }

    public Guid AUTH_Role_ID { get; set; }
}