// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Users_Organizations
{
    public Guid ID { get; set; }

    public Guid? ORG_AUTH_Users_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public string ORG_Fullname { get; set; }

    public string FiscalNumber { get; set; }

    public string VatNumber { get; set; }

    public Guid? AUTH_ORG_Role_ID { get; set; }

    public string Role { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public string CompanyType { get; set; }

    public string LegalForm { get; set; }

    public string User_Fullname { get; set; }

    public string User_FiscalNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ConfirmedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeaktivatedAt { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }
}