// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Municipal_UserLogins
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipal_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LoginTime { get; set; }

    public bool Success { get; set; }

    public string Code { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public string Text { get; set; }
}