// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_AUTH_Municipality
{
    public Guid ID { get; set; }

    [StringLength(250)]
    public string InternalName { get; set; }

    public string Name_Text_SystemTexts_Code { get; set; }

    public string Prefix_Text_SystemTexts_Code { get; set; }

    public byte[] Logo { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public string Text { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public string Text_IT { get; set; }

    public string Address { get; set; }

    public string Location { get; set; }

    public string Phone { get; set; }

    public string Mail { get; set; }

    public string ReportName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MensaPNPrefix { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MensaRefundPNPrefix { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ROOMPNPrefix { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string OrgPNPrefix { get; set; }

    public string Province_Text_SystemTexts_Code { get; set; }
}