// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_DailyList_Report
{
    public Guid ID { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string IsGlutenIntolerance { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string IsLactoseIntolerance { get; set; }

    public string AdditionalIntolerance { get; set; }

    public Guid? CANTEEN_Canteen_ID { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    [StringLength(250)]
    public string InternalName { get; set; }

    public string Text { get; set; }

    public byte[] Logo { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public string Text_IT { get; set; }

    public string MUN_Address { get; set; }

    public string MUN_Location { get; set; }

    public string MUN_Phone { get; set; }

    public string MUN_Mail { get; set; }

    public string MUN_ReportName { get; set; }

    public string Menu_Standard_Text { get; set; }

    public string Menu_SonderMenu_Text { get; set; }

    public string Menu_WithOutPorkMeat_Text { get; set; }

    public string Menu_NoMeat_Text { get; set; }

    public long? AdditionalPersonal { get; set; }

    public string ReportTitle { get; set; }

    [Required]
    [StringLength(101)]
    public string FullName { get; set; }

    public string TITLE_Name { get; set; }

    public string TITLE_GLUTEN { get; set; }

    public string TITLE_LACTOSE { get; set; }

    public string TITLE_ADDITIONAL { get; set; }

    public string TITLE_STANDARD { get; set; }

    [StringLength(17)]
    [Unicode(false)]
    public string Today { get; set; }

    public string TITLE_NO_PORK { get; set; }

    public string TITLE_NO_MEAT { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string NoPork { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string NoMeat { get; set; }

    public int Count_Standard { get; set; }

    public int Count_Gluten { get; set; }

    public int Count_Lactose { get; set; }

    public int Count_NoPork { get; set; }

    public int Count_NoMeat { get; set; }

    public int Count_Additional { get; set; }

    public int Count_Additional_Others { get; set; }

    public string TITLE_COUNT_TOTAL { get; set; }

    public string TITLE_ADDITIONAL_PERSONAL { get; set; }

    public string CanteenName { get; set; }

    public string SchoolName { get; set; }

    public string SchoolClass { get; set; }

    public string TITLE_SCHOOL { get; set; }

    public string TITLE_SCHOOLCLASS { get; set; }

    public string TITLE_ADDITIONAL_OTHERS { get; set; }

    public Guid? CANTEEN_School_ID { get; set; }

    public long? TotalPersonal { get; set; }
}