// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Statistik_Meals
{
    public Guid ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    public bool Used { get; set; }

    public bool UsedWhileCanceled { get; set; }

    public bool ManualCheckIn { get; set; }

    public bool BalanceToLow { get; set; }

    public bool NotAttended { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    public string Child_DomicileProvince { get; set; }

    public string Child_DomicilePostalCode { get; set; }

    public string Child_DomicileMunicipality { get; set; }

    public Guid? Child_Domicile_Municipal_ID { get; set; }

    public int Completed { get; set; }

    public string Meal { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CancelDate { get; set; }

    public string Canteen { get; set; }

    public Guid? CANTEEN_School_ID { get; set; }

    public string School { get; set; }

    public string SchoolClass { get; set; }
}