// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Canteen_With_Pos_Devices
{
    public Guid ID { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public string CANTEEN_Canteen_Name { get; set; }

    public string AUTH_Municipality_Name { get; set; }

    public string CANTEEN_Municipality_Canteen_Name { get; set; }
}