// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Canteen_ExternalAccessLinks
{
    public Guid? ID { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    public Guid CANTEEN_Canteen_ID { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    public string CANTEEN_Canteen_Name { get; set; }

    public string AUTH_Municipality_Name { get; set; }

    public bool? LinkActive { get; set; }

    public string ActionSystemTextCode { get; set; }

    public string ActionSystem { get; set; }

    public string Link { get; set; }

    public Guid? ExternalAccessToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExternalAccessTokenExpirationTime { get; set; }
}