// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Balance_ServiceStop_Notification
{
    public Guid id { get; set; }

    public Guid? AUTH_User_ID { get; set; }

    [StringLength(16)]
    public string TaxNumber { get; set; }

    [StringLength(400)]
    public string FullName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Creationdate { get; set; }

    public Guid? MunicipalityID { get; set; }

    [StringLength(8)]
    public string TelPin { get; set; }

    public int? SubscriberCount { get; set; }

    [Column(TypeName = "decimal(38, 2)")]
    public decimal? Balance { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastNotificationDate { get; set; }
}