// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Canteen_Pos_Devices
{
    public Guid ID { get; set; }

    public Guid CANTEEN_CanteenID { get; set; }

    public Guid AUTH_MunicipalityID { get; set; }

    [StringLength(250)]
    public string AUTH_MunicipalityName { get; set; }

    public bool Canteen_InPreparation { get; set; }

    public string Canteen_Name { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string AUTH_MunicipalityMail { get; set; }

    public string CANTEEN_CanteenMail { get; set; }
}