// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Statistik_Subscribers
{
    public string Child_DomicileProvince { get; set; }

    public string Child_DomicilePostalCode { get; set; }

    public string Child_DomicileMunicipality { get; set; }

    public Guid? Child_Domicile_Municipal_ID { get; set; }

    public string Meal { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? CanteenID { get; set; }

    public Guid? SchoolID { get; set; }

    public string Canteen { get; set; }

    public string School { get; set; }

    public string SchoolClass { get; set; }

    public Guid? SchoolyearID { get; set; }

    public Guid? CANTEEN_Subscriber_Status_ID { get; set; }

    public bool DayMo { get; set; }

    public bool DayTue { get; set; }

    public bool DayWed { get; set; }

    public bool DayThu { get; set; }

    public bool DayFri { get; set; }
}