// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Statistic_Students
{
    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? CANTEEN_Canteen_ID { get; set; }

    public string CanteenName { get; set; }

    public Guid? CANTEEN_School_ID { get; set; }

    public string SchoolName { get; set; }

    public Guid? CanteenMenuID { get; set; }

    public string SchoolClass { get; set; }

    public Guid? SchoolClassID { get; set; }

    public string MenuTextCode { get; set; }

    public bool DayMo { get; set; }

    public bool DayTue { get; set; }

    public bool DayWed { get; set; }

    public bool DayThu { get; set; }

    public bool DayFri { get; set; }

    public bool DaySat { get; set; }

    public bool DaySun { get; set; }

    public bool IsLactoseIntolerance { get; set; }

    public bool IsGlutenIntolerance { get; set; }

    [Required]
    [StringLength(101)]
    public string FullName { get; set; }

    [Required]
    [StringLength(50)]
    public string TaxNumber { get; set; }

    public string AdditionalIntolerance { get; set; }

    public Guid LANG_LanguagesID { get; set; }
}