// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Subscribers_To_Archive
{
    public Guid ID { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    public Guid? SchoolyearID { get; set; }

    [StringLength(20)]
    public string SchoolyearDescription { get; set; }

    public Guid? CANTEEN_Subscriber_Status_ID { get; set; }

    public string StatusCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BeginDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public Guid? MunicipalityId { get; set; }
}