// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Subscriber_Card_Status
{
    public int ID { get; set; }

    public string Status { get; set; }

    public string Icon { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public bool IsSelectable { get; set; }
}