// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Schoolyear
{
    public Guid id { get; set; }

    [StringLength(50)]
    public string DisplayText { get; set; }

    public int BeginYear { get; set; }

    public int? EndYear { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BeginDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndDate { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public int? SubscriberCount { get; set; }
}