// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Tax_Report_Subscribers
{
    public Guid? AUTH_Users_ID { get; set; }

    [Required]
    [StringLength(50)]
    public string TaxNumber { get; set; }

    [Required]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Required]
    [StringLength(50)]
    public string LastName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Child_DateOfBirth { get; set; }

    public string Child_PlaceOfBirth { get; set; }
}