// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Subscriber_Card
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string AUTH_Municipality_Name { get; set; }

    public string CardID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public string Taxnumber { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public int? CANTEEN_Subscriber_Card_Status_ID { get; set; }

    public string MunicipalityPath { get; set; }

    public string MunicipalityText { get; set; }

    public string DEST_Name { get; set; }

    public string DEST_Address { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FinishDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NewRequestDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DisabledDate { get; set; }

    public string PlaceOfBirth { get; set; }

    public string StatusIcon { get; set; }

    public string Status { get; set; }

    public Guid LANG_LanguagesID { get; set; }
}