// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Subscriber_Movements
{
    public Guid ID { get; set; }

    public Guid? CANTEEN_Subscriber_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    [Column(TypeName = "money")]
    public decimal? Fee { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [StringLength(50)]
    public string FirstName { get; set; }

    [StringLength(50)]
    public string LastName { get; set; }

    [StringLength(50)]
    public string TaxNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Child_DateOfBirth { get; set; }

    [StringLength(20)]
    public string SchoolClassNumber { get; set; }

    [StringLength(50)]
    public string SchoolClass { get; set; }

    [StringLength(500)]
    public string SchoolName { get; set; }

    public Guid? CANTEEN_Canteen_ID { get; set; }

    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CancelDate { get; set; }

    public Guid? CANTEEN_Subscriber_Movement_Type_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedDate { get; set; }

    public Guid? AUTH_User_ID { get; set; }

    public Guid? PaymentTransactionID { get; set; }

    [StringLength(100)]
    public string Info { get; set; }

    public bool? IsManual { get; set; }

    public bool IsMunicipalInput { get; set; }

    public Guid? CANTEEN_RequestRefundBalancesID { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentDate { get; set; }

    public Guid? RefundReferenceID { get; set; }

    public bool? IsRefund { get; set; }

    public bool Used { get; set; }

    public bool UsedWhileCanceled { get; set; }
}