// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Entratel
{
    [Column("Eltern Name")]
    [StringLength(400)]
    public string Eltern_Name { get; set; }

    [Column("Eltern Steuernummer")]
    [StringLength(16)]
    public string Eltern_Steuernummer { get; set; }

    [Column("Kind Name")]
    [StringLength(101)]
    public string Kind_Name { get; set; }

    [Column("Kind Steuernummer")]
    [StringLength(50)]
    public string Kind_Steuernummer { get; set; }

    [Column(TypeName = "money")]
    public decimal Bezahlt { get; set; }

    [Column(TypeName = "money")]
    public decimal Rueckerstattung { get; set; }
}