// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Subscriber_Card_Status_Log
{
    public Guid ID { get; set; }

    public Guid? CANTEEN_Subscriber_Card_ID { get; set; }

    public int? CANTEEN_Subscriber_Card_Status_ID { get; set; }

    public string Status { get; set; }

    public string StatusIcon { get; set; }

    public Guid LANG_LanguagesID { get; set; }
}