// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Configuration
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public string AUTH_Municipality_Name { get; set; }

    [Column(TypeName = "money")]
    public decimal? BalanceLowWarning { get; set; }

    [Column(TypeName = "money")]
    public decimal? BalanceLowServiceStop { get; set; }

    public long? ReminderIntervallDays { get; set; }

    [Column(TypeName = "money")]
    public decimal? RechargeMinAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastBalanceLowWarningListSent { get; set; }

    public bool ServiceStopEnabled { get; set; }

    public bool AllowCanteenDeregistrationIfServiceStopEnabled { get; set; }

    public bool PosMode { get; set; }

    public int RequestCardInterval { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal NewPosCardPrice { get; set; }
}