// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CANTEEN_Student
{
    public Guid? AUTH_Municipality_ID { get; set; }

    public string Taxnumber { get; set; }

    public string Firstname { get; set; }

    public string Lastname { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    public int ActiveSubscription { get; set; }
}