// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CHAT_Message_Document
{
    public Guid ID { get; set; }

    public Guid CHAT_Message_ID { get; set; }

    public Guid FILE_FileInfo_ID { get; set; }

    [Required]
    [StringLength(255)]
    [Unicode(false)]
    public string ContextElementId { get; set; }

    [StringLength(500)]
    public string FileName { get; set; }

    [StringLength(10)]
    public string FileExtension { get; set; }

    public long? Size { get; set; }
}