// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_CONF_Freshdesk_Priority
{
    public long ID { get; set; }

    public string Text_SystemTexts_Code { get; set; }

    public long? SortOrder { get; set; }

    public string Text { get; set; }

    public Guid LANG_LanguagesID { get; set; }
}