// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_DASH_UserChat
{
    public Guid Application_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EingereichtAm { get; set; }

    public Guid? Responsible_AUTH_Users_ID { get; set; }

    public string FormName { get; set; }

    public string ChatMessage { get; set; }

    public bool? ChatMessageUnread { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChatLastMessageDate { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string CitizenName { get; set; }
}