// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Definition_Municipal_Field
{
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? FORM_Definition_Municipal_Field_Type_ID { get; set; }

    public long? SortOrder { get; set; }

    public string Description { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    public string Type { get; set; }
}