// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Definition_Deadline_Estimated_Notifications
{
    public Guid ID { get; set; }

    public Guid FORM_Definition_Deadline_ID { get; set; }

    public Guid? AUTH_Municpal_Users_ID { get; set; }

    public Guid ApplicationID { get; set; }

    public Guid DefinitionID { get; set; }

    public Guid? AUTH_Authority_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstimatedDeadline { get; set; }

    public long? AdditionalDays { get; set; }

    public Guid? FORM_Definition_Deadlines_TimeType_ID { get; set; }
}