// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Application_Personal_Area
{
    public Guid ID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? FORM_Application_Status_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubmitAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SignedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PayedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BolloAt { get; set; }

    [Unicode(false)]
    public string Price { get; set; }

    public Guid? FILE_Fileinfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public bool IsEskalated { get; set; }

    public bool IsManualInput { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LegalDeadline { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstimatedDeadline { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FiscalNumber { get; set; }

    public string Email { get; set; }

    public string CountyOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string DomicileMunicipality { get; set; }

    public string DomicileNation { get; set; }

    public string DomicilePostalCode { get; set; }

    public string DomicileProvince { get; set; }

    public string DomicileStreetAddress { get; set; }

    public string Gender { get; set; }

    public string MobilePhone { get; set; }

    public string RegisteredOffice { get; set; }

    public string Mantainance_Title { get; set; }

    public string Mantainance_Description { get; set; }

    public string Mantainance_Lan { get; set; }

    public string Mantainance_Lat { get; set; }

    public Guid? FORM_Application_Priority_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Archived { get; set; }

    public long? PDFPageCount { get; set; }

    [Column(TypeName = "money")]
    public decimal? Credit { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PrivacyReadAt { get; set; }

    public Guid? ROOT_AUTH_User_ID { get; set; }

    public string ROOT_FirstName { get; set; }

    public string ROOT_LastName { get; set; }

    public string ROOT_FiscalCode { get; set; }

    public string ROOT_CountyOfBirth { get; set; }

    public string ROOT_PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ROOT_DateOfBirth { get; set; }

    public string VATNumber { get; set; }

    public Guid? GV_AUTH_User_ID { get; set; }

    public string GV_FirstName { get; set; }

    public string GV_LastName { get; set; }

    public string GV_FiscalCode { get; set; }

    public string GV_CountyOfBirth { get; set; }

    public string GV_PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? GV_DateOfBirth { get; set; }

    public string ROOT_Email { get; set; }

    public string ROOT_DomicileMunicipality { get; set; }

    public string ROOT_DomicileNation { get; set; }

    public string ROOT_DomicilePostalCode { get; set; }

    public string ROOT_DomicileProvince { get; set; }

    public string ROOT_DomicileStreetAddress { get; set; }

    public string ROOT_Gender { get; set; }

    public string ROOT_Phone { get; set; }

    public string ROOT_MobilePhone { get; set; }

    public string GV_Email { get; set; }

    public string GV_DomicileMunicipality { get; set; }

    public string GV_DomicileNation { get; set; }

    public string GV_DomicilePostalCode { get; set; }

    public string GV_DomicileProvince { get; set; }

    public string GV_DomicileStreetAddress { get; set; }

    public string GV_Gender { get; set; }

    public string GV_Phone { get; set; }

    public string GV_MobilePhone { get; set; }

    public string ROOT_Address { get; set; }

    public string GV_Address { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NotificationSendDate { get; set; }

    public string IBAN { get; set; }

    public string Bankname { get; set; }

    public string KontoInhaber { get; set; }

    public long? ProgressivYear { get; set; }

    public long? ProgressivNumber { get; set; }

    public Guid? TASK_Task_ID { get; set; }

    public bool IsMunicipal { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? MunicipalDeadline { get; set; }

    public bool? IsMunicipalCommittee { get; set; }

    public string TemplateJsonData { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PreviewSeenAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentReminderSentAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaymentStarted { get; set; }

    public Guid? FORM_Definition_Category_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string FormName { get; set; }

    public string ShortText { get; set; }

    public string Authority { get; set; }

    public string AuthorityIcon { get; set; }

    public string Status { get; set; }

    public string StatusIcon { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StatusChangeDate { get; set; }

    [Unicode(false)]
    public string FullProgressivNumber { get; set; }

    public int OpenPayments { get; set; }
}