// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Application_Report
{
    public Guid ID { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? FORM_Application_Status_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubmitAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SignedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PayedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BolloAt { get; set; }

    [Unicode(false)]
    public string Price { get; set; }

    public Guid? FILE_Fileinfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public bool IsEskalated { get; set; }

    public bool IsManualInput { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LegalDeadline { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstimatedDeadline { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ComposedName { get; set; }

    public string FiscalNumber { get; set; }

    public string Email { get; set; }

    public string CountyOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string DomicileMunicipality { get; set; }

    public string DomicileNation { get; set; }

    public string DomicilePostalCode { get; set; }

    public string DomicileProvince { get; set; }

    public string DomicileStreetAddress { get; set; }

    public string Gender { get; set; }

    public string MobilePhone { get; set; }

    public string RegisteredOffice { get; set; }

    public string FORM_Description { get; set; }

    public string FORM_Name { get; set; }

    [StringLength(250)]
    public string InternalName { get; set; }

    public string Text { get; set; }

    public byte[] Logo { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public string Text_IT { get; set; }

    public string MUN_Address { get; set; }

    public string MUN_Location { get; set; }

    public string MUN_Phone { get; set; }

    public string MUN_Mail { get; set; }

    public string MUN_ReportName { get; set; }

    public string AMT_DE { get; set; }

    public string AMT_IT { get; set; }

    public string Authority_Mail { get; set; }

    public string Authority_Phone { get; set; }

    [Column(TypeName = "money")]
    public decimal? PayedAmount { get; set; }

    public string TEXT_COMITTED { get; set; }

    public string TEXT_BIRTH { get; set; }

    public string TEXT_BOLLO { get; set; }

    public string TEXT_PROTOCOLLNR { get; set; }

    public string TEXT_PAYMENT { get; set; }

    public string PhoneComposed { get; set; }

    public string ComposedMail { get; set; }

    public long? PDFPageCount { get; set; }

    [Column(TypeName = "money")]
    public decimal? Credit { get; set; }

    public string ComposedCredit { get; set; }

    public string BOLLO_VAL { get; set; }

    public string Description { get; set; }

    public string Title { get; set; }

    public int ShowPrivacy { get; set; }

    public string TEXT_BOLLO_SHORT { get; set; }

    public bool HasBollo { get; set; }

    public Guid? ROOT_AUTH_User_ID { get; set; }

    public string ROOT_FirstName { get; set; }

    public string ROOT_LastName { get; set; }

    public string ROOT_FiscalCode { get; set; }

    public string ROOT_CountyOfBirth { get; set; }

    public string ROOT_PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ROOT_DateOfBirth { get; set; }

    public string ROOT_Name { get; set; }

    public bool? HasRootUser { get; set; }

    public string VATNumber { get; set; }

    public string TEXT_SUBMITTED_FROM { get; set; }

    public string TEXT_GV { get; set; }

    public Guid? GV_AUTH_User_ID { get; set; }

    public string GV_FirstName { get; set; }

    public string GV_LastName { get; set; }

    public string GV_FiscalCode { get; set; }

    public string GV_CountyOfBirth { get; set; }

    public string GV_PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? GV_DateOfBirth { get; set; }

    public string GV_Name { get; set; }

    public bool? HasGVUser { get; set; }

    public string TEXT_GV_BIRTH { get; set; }

    public string TEXT_ROOT_BIRTH { get; set; }

    public string ROOT_Email { get; set; }

    public string ROOT_Address { get; set; }

    public string ROOT_DomicileMunicipality { get; set; }

    public string ROOT_DomicileNation { get; set; }

    public string ROOT_DomicilePostalCode { get; set; }

    public string ROOT_DomicileProvince { get; set; }

    public string ROOT_DomicileStreetAddress { get; set; }

    public string ROOT_Gender { get; set; }

    public string ROOT_MobilePhone { get; set; }

    public string ROOT_Phone { get; set; }

    public string GV_Email { get; set; }

    public string GV_Address { get; set; }

    public string GV_DomicileMunicipality { get; set; }

    public string GV_DomicileNation { get; set; }

    public string GV_DomicilePostalCode { get; set; }

    public string GV_DomicileProvince { get; set; }

    public string GV_DomicileStreetAddress { get; set; }

    public string GV_Gender { get; set; }

    public string GV_MobilePhone { get; set; }

    public string GV_Phone { get; set; }

    public bool? BolloFree { get; set; }

    public string AUTH_BolloFree_Reason { get; set; }

    public string Authority_MailIT { get; set; }

    public bool? HasRootUserInverted { get; set; }

    public bool? HasGVUserInverted { get; set; }

    public string FiscalData { get; set; }

    public string IBAN { get; set; }

    public string Kontoinhaber { get; set; }

    public string Bankname { get; set; }

    public string BANKDATA_TITLE { get; set; }

    public int HasIBAN { get; set; }
}