// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Application_Deadlines
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubmitAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LegalDeadline { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstimatedDeadline { get; set; }

    public Guid DeadlineID { get; set; }

    public long? DeadlineDays { get; set; }

    public Guid? FORM_Definition_Deadlines_TimeType_ID { get; set; }
}