// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Application_Status_Statistik
{
    public Guid ID { get; set; }

    public Guid? AUTH_Authority_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public long? SortOrder { get; set; }

    public string Icon { get; set; }

    public string TEXT_SystemTexts_Code { get; set; }

    public int? ApplicationCount { get; set; }
}