// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_FORM_Application_Report_Response
{
    public Guid ID { get; set; }

    public Guid? LANG_LanguagesID { get; set; }

    public Guid? FORM_Definition_ID { get; set; }

    public Guid? FORM_Application_Status_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SubmitAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? SignedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PayedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BolloAt { get; set; }

    [Unicode(false)]
    public string Price { get; set; }

    public Guid? FILE_Fileinfo_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RemovedAt { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public bool IsEskalated { get; set; }

    public bool IsManualInput { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LegalDeadline { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EstimatedDeadline { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ComposedName { get; set; }

    public string FiscalNumber { get; set; }

    public string Email { get; set; }

    public string CountyOfBirth { get; set; }

    public string PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfBirth { get; set; }

    public string Address { get; set; }

    public string DomicileMunicipality { get; set; }

    public string DomicileNation { get; set; }

    public string DomicilePostalCode { get; set; }

    public string DomicileProvince { get; set; }

    public string DomicileStreetAddress { get; set; }

    public string Gender { get; set; }

    public string MobilePhone { get; set; }

    public string RegisteredOffice { get; set; }

    public string FORM_Description { get; set; }

    public string FORM_Name { get; set; }

    [StringLength(250)]
    public string InternalName { get; set; }

    public string Text { get; set; }

    public byte[] Logo { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public string Text_IT { get; set; }

    public string MUN_Address { get; set; }

    public string MUN_Location { get; set; }

    public string MUN_Phone { get; set; }

    public string MUN_Mail { get; set; }

    public string MUN_ReportName { get; set; }

    public string AMT_DE { get; set; }

    public string AMT_IT { get; set; }

    public string Authority_Mail { get; set; }

    public string Authority_Phone { get; set; }

    public string ReportTitle { get; set; }

    public string ReportReason { get; set; }

    public Guid? ROOT_AUTH_User_ID { get; set; }

    public string ROOT_FirstName { get; set; }

    public string ROOT_LastName { get; set; }

    public string ROOT_FiscalCode { get; set; }

    public string ROOT_CountyOfBirth { get; set; }

    public string ROOT_PlaceOfBirth { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ROOT_DateOfBirth { get; set; }

    public string ROOT_Name { get; set; }

    public int HasRootUser { get; set; }

    public string VATNumber { get; set; }

    public string ProgressivNumber { get; set; }
}