// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_HOME_Municipality
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string Telefon { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public double? Lat { get; set; }

    public double? Lang { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Description { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string PecEMail { get; set; }

    public string EMail { get; set; }
}