// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_HOME_Organisation
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? HOME_Organisation_Type_ID { get; set; }

    public Guid? Managed_HOME_Person_ID { get; set; }

    public Guid? Managed_AUTH_Authority_ID { get; set; }

    public Guid? HOME_Organisation_ID { get; set; }

    public Guid? HOME_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public bool Highlight { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    public string ContactName { get; set; }

    public string ContactEMail { get; set; }

    public string ContactPhone { get; set; }

    public string ContactPECMail { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    public string Description { get; set; }

    public string DescriptionShort { get; set; }

    public string Type { get; set; }

    public string Title { get; set; }

    public string Responsibility { get; set; }

    public string Themes { get; set; }
}