// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_HOME_Appointment_Dates
{
    public Guid Id { get; set; }

    public Guid HOME_AppointmentID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public Guid? Managed_HOME_Person_ID { get; set; }

    public Guid? HOME_Organisation_ID { get; set; }

    public string Address { get; set; }

    public string Room { get; set; }

    public Guid? FILE_FileImage_ID { get; set; }

    public Guid? HOME_Appointment_Type_ID { get; set; }

    public bool Highlight { get; set; }

    public Guid? HOME_Appointment_Kategorie_ID { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string DescriptionShort { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateTo { get; set; }

    public Guid Dates_ID { get; set; }

    public string Type { get; set; }

    public string Kategorie { get; set; }

    public string Themes { get; set; }

    public string ContactName { get; set; }

    public string ContactPhone { get; set; }

    public string ContactEmail { get; set; }

    public string ContactPhoneMobile { get; set; }

    public string ContactWebsite { get; set; }

    public string ContactAddress { get; set; }

    public double? ContactLat { get; set; }

    public double? ContactLang { get; set; }

    public double? Lat { get; set; }

    public double? Lang { get; set; }
}