// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_HOME_Organisation_Person_Type
{
    public Guid ID { get; set; }

    public string Title { get; set; }

    public Guid LANG_LanguagesID { get; set; }

    public string Group { get; set; }

    public string GroupCode { get; set; }

    public int? GroupSortOrderID { get; set; }
}