// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_HOME_Article
{
    public Guid ID { get; set; }

    public bool Highlight { get; set; }

    public int? ReadDuration { get; set; }

    public Guid? FILE_FileInfo_ID { get; set; }

    public bool Visible { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastModificationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReleaseDate { get; set; }

    public Guid? Managed_HOME_Person_ID { get; set; }

    public Guid? Managed_AUTH_Authority_ID { get; set; }

    public Guid AUTH_Municipality_ID { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    public Guid? HOME_Article_Type_ID { get; set; }

    public string Content { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Subject { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public string ShortText { get; set; }

    public string Themes { get; set; }
}