// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_HOME_Person
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastChangeDate { get; set; }

    public string Name { get; set; }

    public string Lastname { get; set; }

    public Guid? FILE_FileImage_ID { get; set; }

    public string PhoneNr { get; set; }

    public Guid? HOME_Person_Type_ID { get; set; }

    public bool Highlight { get; set; }

    public string PhoneNrPrivat { get; set; }

    public string PhoneNrMobile { get; set; }

    public bool Gender { get; set; }

    public bool AllowTimeslots { get; set; }

    public int MinDaysAheadOfBooking { get; set; }

    public int MaxDaysBookable { get; set; }

    public bool AllowOfficeHours { get; set; }

    public double? Lat { get; set; }

    public double? Lang { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public string Description { get; set; }

    public string DescriptionShort { get; set; }

    public string AreaOfWork { get; set; }

    public string EMail { get; set; }

    public string EMail2 { get; set; }

    public string PECEmail { get; set; }

    public string Tasks { get; set; }

    public string Address { get; set; }

    public string Room { get; set; }

    public string Type { get; set; }
}