// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_PAY_Bollo_To_Pay
{
    public Guid ID { get; set; }

    [Column(TypeName = "money")]
    public decimal? Amount { get; set; }

    public string Description { get; set; }

    public long? SortOrder { get; set; }

    public Guid? PAY_Transaction_ID { get; set; }

    public bool IsFee { get; set; }

    public bool IsBollo { get; set; }

    public string BolloNumber { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RefundDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BolloCreationDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ICPayedAt { get; set; }

    public string UserName { get; set; }

    public string FiscalNumber { get; set; }
}