// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_Privacy_Report
{
    [StringLength(250)]
    public string InternalName { get; set; }

    public string Text { get; set; }

    public byte[] Logo { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    public string Text_IT { get; set; }

    public string MUN_Address { get; set; }

    public string MUN_Location { get; set; }

    public string MUN_Phone { get; set; }

    public string MUN_Mail { get; set; }

    public string MUN_ReportName { get; set; }

    public string Description { get; set; }

    public string Title { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }
}