// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_ROOM_RoomOptions_Positions
{
    public Guid ID { get; set; }

    public Guid? ROOM_Rooms_Options_ID { get; set; }

    public long? Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    public string User { get; set; }
}