// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_ROOM_Settings
{
    public Guid ID { get; set; }

    public string DefaultRoomOptions { get; set; }

    public bool HasTasks { get; set; }

    public int? MaxRoomBookingDays { get; set; }

    public int? MinRoomBookingDays { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public string ForWhom { get; set; }

    public string HowTo { get; set; }

    public string WhatFor { get; set; }

    public string Result { get; set; }

    public Guid? LANG_Language_ID { get; set; }
}