// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_ROOM_Booking_Status_Log
{
    public Guid ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChangeDate { get; set; }

    public Guid? AUTH_Users_ID { get; set; }

    public Guid? ROOM_BookingGroup_ID { get; set; }

    public Guid? ROOM_BookingStatus { get; set; }

    public string Reason { get; set; }

    public string Title { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    public string IconCSS { get; set; }

    public string Status { get; set; }

    public string User { get; set; }
}