// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_ROOM_RoomOptions_Contact
{
    public Guid ID { get; set; }

    public Guid? ROOM_RoomOptions_ID { get; set; }

    public Guid? CONT_Contact_ID { get; set; }

    public bool SendEmail { get; set; }

    public bool SendSMS { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string EMail { get; set; }

    public string Phone { get; set; }
}