// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_ROOM_RoomOptions
{
    public Guid ID { get; set; }

    public Guid ROOM_Room_ID { get; set; }

    public double? BasePrice { get; set; }

    public bool? DailyPayment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public int? Pos { get; set; }

    public Guid? ROOM_RoomOptions_Category_ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public bool? Enabled { get; set; }

    public string Category { get; set; }

    public int? CountContacts { get; set; }

    public long? Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastInvetory { get; set; }
}