// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_ROOM_Rooms
{
    public Guid ID { get; set; }

    public Guid MunicipalityID { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string MaxCapacity { get; set; }

    public double? Lat { get; set; }

    public double? Lng { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string SurfaceM2 { get; set; }

    public bool Enabled { get; set; }

    public Guid? RoomGroupFamilyID { get; set; }

    [StringLength(50)]
    public string RoomColor { get; set; }

    public bool HasDirectPay { get; set; }

    public bool HasSigning { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Address { get; set; }

    public string Location { get; set; }

    public Guid? LANG_Languages_ID { get; set; }

    public bool HasRooms { get; set; }

    public string BuildingName { get; set; }

    public Guid? PricingType { get; set; }

    public int? QuantityOfSubRooms { get; set; }

    public bool HasSeating { get; set; }

    public int? Seating_Concert { get; set; }

    public int? Seating_Theatre { get; set; }

    public int? Seating_Banquet_Round { get; set; }

    public int? Seating_Banquet_Square { get; set; }

    [StringLength(1000)]
    public string FirstImagePath { get; set; }

    public int? BufferTime { get; set; }

    public bool? BuildingEnabled { get; set; }
}