// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_SYS_Statistic_Municipality_MonthCanteen
{
    public Guid? AUTH_Users_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreationDate { get; set; }

    public Guid? SubscriptionFamilyID { get; set; }

    public int Signed { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public bool IsManualInput { get; set; }

    public int? CreatedMonth { get; set; }

    public int? CreatedYear { get; set; }

    public int? Children { get; set; }
}