// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_TASK_Task
{
    public Guid ID { get; set; }

    public Guid? TASK_Status_ID { get; set; }

    public Guid? TASK_Priority_ID { get; set; }

    [Unicode(false)]
    public string Title { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Deadline { get; set; }

    public Guid? TASK_Bucket_ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CompletedAt { get; set; }

    public Guid? CompletedByAUTH_Municipal_User_ID { get; set; }

    public string Url { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChangeDate { get; set; }

    public long? TASK_Context_ID { get; set; }

    [Unicode(false)]
    public string ContextElementID { get; set; }

    [Unicode(false)]
    public string ContextName { get; set; }

    public long? SortOrder { get; set; }

    public string ContextExternalID { get; set; }

    public Guid? CreatedByAUTH_Municipal_User_ID { get; set; }

    public bool? NotifyCreator { get; set; }

    [Unicode(false)]
    public string StatusIcon { get; set; }

    public string StatusText { get; set; }

    [Unicode(false)]
    public string PriorityIcon { get; set; }

    public string PriorityText { get; set; }

    [Unicode(false)]
    public string BucketIcon { get; set; }

    public string BucketText { get; set; }

    public Guid? LANG_Language_ID { get; set; }

    [Unicode(false)]
    public string ResponsibleUser { get; set; }

    [Unicode(false)]
    public string SelectedTags { get; set; }
}