// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_TASK_Statistik
{
    public long? TASK_Context_ID { get; set; }

    [Unicode(false)]
    public string ContextElementID { get; set; }

    [Unicode(false)]
    public string ContextName { get; set; }

    public int? AllTasks { get; set; }

    public int? OpenTasks { get; set; }

    public int? CompletedTasks { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }
}