// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels;

[Keyless]
public partial class V_TEXT_Template
{
    public Guid ID { get; set; }

    public Guid? AUTH_Municipality_ID { get; set; }

    public Guid? APP_Applications_ID { get; set; }

    public string ExternalContext { get; set; }

    public string ExternalID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    public long? SortOrder { get; set; }

    public bool? IsDocument { get; set; }

    public string Content { get; set; }

    public string Name { get; set; }

    public Guid? LANG_Languages_ID { get; set; }
}