// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels
{
    public partial class CONT_Contact
    {
        [NotMapped]
        public string Fullname
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
        [NotMapped]
        [Required]
        public string FirstNameReq 
        {
            get 
            {
                return FirstName;
            }
            set
            {
                FirstName = value;
            }
        }
        [NotMapped]
        [Required]
        public string LastNameReq
        {
            get
            {
                return LastName;
            }
            set
            {
                LastName = value;
            }
        }
    }
}