// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels
{
    public partial class HOME_Municipal_Newsletter_Extended
    {
       [NotMapped] public FILE_FileInfo? Image { get; set; }
       [NotMapped] public FILE_FileInfo? File { get; set; }
    }
}