// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels
{
    public partial class ROOM_RoomOptions
    {
        [NotMapped] public List<ROOM_RoomOptions_Contact>? Contacts { get; set; } = new List<ROOM_RoomOptions_Contact>();
    }
}