// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels
{
    public partial class ROOM_Rooms_Contact
    {
        [NotMapped]
        public string Fullname
        {
            get
            {
                if (CONT_Contact != null)
                    return CONT_Contact.Fullname;

                return "";
            }
        }
    }
}