// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels
{
    public partial class V_HOME_Person
    {
        [NotMapped]
        public string Fullname
        {
            get
            {
                return this.Name + " " + this.Lastname;
            }
        }
        [NotMapped]
        public string SearchField
        {
            get
            {
                return this.Name + " " + this.Lastname + " " + this.Name + " " + this.Tasks;
            }
        }
        [NotMapped]
        public string Color { get; set; } = "#0f7173";
        [NotMapped]
        public Guid Id
        {
            get
            {
                return ID;
            }
            set
            {
                ID = value;
            }
        }
    }
}