// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ICWebApp.Domain.DBModels
{
    public partial class V_TASK_Task
    {
        [NotMapped]
        public bool Refresh { get; set; } = true;
        [NotMapped]
        public bool Filtered { get; set; } = false;
    }
}