using ICWebApp.Application.Settings;
using ICWebApp.Domain.DBModels;
using Microsoft.Identity.Client;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ICWebApp.Application.Interface.Provider
{
    public interface IHOMEProvider
    {
        public List<V_HOME_Appointment> GetCurrentMonthEvents(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Appointment>> GetAppointments(Guid AUTH_Municipality_ID);
        public Task<V_HOME_Association?> GetVAssociation(Guid ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Appointment_Dates>> GetAppointmentsWithDates(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Theme>> GetThemesByAssociation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Association_ID);
        public Task<List<V_HOME_Person>> GetPeopleByAssociation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Association_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByAssociation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Association_ID);
        public Task<List<V_HOME_Appointment>> GetAppointmentsWithDatesByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Appointment_Type_ID);
        public Task<List<V_HOME_Association>> GetAssociationByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Association_Type_ID);
        public Task<List<V_HOME_Appointment_Dates>> GetAppointmentsByThemes(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Theme_ID);
        public Task<List<V_HOME_Venue>> GetVenuesByThemes(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Theme_ID);
        public Task<List<V_HOME_Venue>> GetVenuesByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Venue_Type_ID);
        public Task<List<V_HOME_Person>> GetPersonByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Person_Type_ID);
        public Task<List<V_HOME_Venue>> GetVenuesByPerson(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Person_ID);
        public Task<List<V_HOME_Authority>> GetAuthoritiesByPerson(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Person_ID);
        public Task<List<V_HOME_Association>> GetAssociationsByPerson(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Person_ID);
        public Task<List<V_HOME_Organisation>> GetOrganisationsByPerson(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Person_ID);
        public Task<List<V_HOME_Organisation>> GetOrganisationsByDocument(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Document_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByPerson(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Person_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByAuthority(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Authority_ID);
        public Task<List<V_HOME_Article>> GetArticles(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Article>> GetArticlesByTheme(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Theme_ID);
        public List<V_HOME_Article_Theme> GetVThemesByArticle(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Article_ID);
        public Task<List<V_HOME_Theme>> GetThemesByArticle(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Article_ID);
        public Task<List<V_HOME_Theme>> GetThemesByVenue(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Venue_ID);
        public Task<List<V_HOME_Theme>> GetThemesByAuthority(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Authority_ID);
        public Task<List<V_HOME_Theme>> GetThemesByDocument(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Document_ID);
        public Task<List<V_HOME_Document_Type>> GetDocument_TypeByDocument(Guid HOME_Document_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Article>> GetArticlesByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Article_Type_ID);
        public Task<V_HOME_Article_Type> GetArticle_Type(Guid HOME_Article_Type_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Organisation>> GetOrganisationsByTheme(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Theme_ID);
        public Task<List<V_HOME_Organisation>> GetOrganisationsByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Type_ID);
        public Task<List<V_HOME_Location>> GetLocationByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Location_Type_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByTheme(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Theme_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Document_Type_ID);
        public Task<List<V_HOME_Association>> GetAssociations(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Authority>> GetAuthorities(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Faq>> GetFaqs(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<V_HOME_Authority?> GetAuthority(Guid ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Document>> GetDocuments(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Media>> GetMediaList(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<HOME_Media_Extended>> GetMediaExtended(Guid HOME_Media_ID);
        public Task<HOME_Media_Extended?> SetMediaExtended(HOME_Media_Extended Data);
        public Task<HOME_Media?> GetMedia(Guid ID);
        public Task<int> GetMediaSortOrder(Guid AUTH_Municipality_ID);
        public Task<int> GetImpressumSortOrder(Guid AUTH_Municipality_ID);
        public Task<int> GetPNRRSortOrder(Guid AUTH_Municipality_ID);
        public Task<int> GetPNRRChapterSortOrder(Guid AUTH_Municipality_ID);
        public Task<int> GetPrivacySortOrder(Guid AUTH_Municipality_ID);
        public Task<HOME_Media?> SetMedia(HOME_Media Data);
        public Task<bool> RemoveMedia(Guid ID);
        public Task<List<V_HOME_Document_Format>> GetDocument_Formats(Guid LANG_Language_ID);
        public Task<List<V_HOME_Document_License>> GetDocument_Licenses(Guid LANG_Language_ID);
        public Task<List<V_HOME_Document_Type>> GetDocument_Types(Guid LANG_Language_ID);
        public Task<V_HOME_Document_Type?> GetDocument_Type(Guid ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Municipal_Newsletter>> GetMunicipalNewsletters(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Municipal_Newsletter>> GetMunicipalNewsletters(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, int Amount = 3);
        public Task<List<V_HOME_Municipal_Newsletter>> GetMunicipalNewslettersByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Municipal_Newsletter_Type_ID);
        public Task<List<V_HOME_Municipality>> GetMunicipalities(Guid AUTH_Municipality_ID);
        public Task<List<V_HOME_Organisation>> GetOrganisations(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Organisation_Type>> GetOrganisation_Types(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Person_Type>> GetPerson_Types(Guid LANG_Language_ID);
        public Task<List<V_HOME_Person>> GetPeople(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Person>> GetPeopleWithTimeslots(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Person>> GetPeopleByAuthority(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid AUTH_Authority_ID);
        public Task<List<V_HOME_Person>> GetPeopleByVenue(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Venue_ID);
        public Task<List<V_HOME_Person>> GetPeopleByDocument(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Document_ID);
        public Task<List<V_HOME_Questionnaire>> GetQuestionnaires(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public List<V_HOME_Theme> GetThemes(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Theme_Type>> GetTheme_Types(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Venue>> GetVenues(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, bool OnlyHighlights = false);
        public Task<List<V_HOME_Venue_Type>> GetVenue_Types(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Location_Type>> GetLocation_Types(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<HOME_Location_Type_Extended>> GetLocation_Type_Extended(Guid HOME_Location_Type_ID);
        public Task<HOME_Location_Type?> GetLocationType(Guid HOME_Location_Type_ID);
        public Task<HOME_Location_Type?> SetLocationType(HOME_Location_Type Data);
        public Task<HOME_Location_Type_Extended?> SetLocationTypeExtended(HOME_Location_Type_Extended Data);
        public Task<bool> RemoveLocationType(HOME_Location_Type Data);
        public Task<bool> RemoveLocationType(Guid HOME_Location_Type_ID);
        public Task<HOME_Appointment?> GetAppointment(Guid ID);
        public Task<V_HOME_Appointment?> GetVAppointment(Guid HOME_AppointmentID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Appointment_Dates>> GetVAppointmentDates(Guid HOME_AppointmentID, Guid LANG_Language_ID);
        public Task<List<HOME_Appointment_Dates>> GetAppointment_Dates(Guid HOME_Appointment_ID);
        public Task<HOME_Appointment_Dates?> GetAppointmentDate(Guid ID);
        public Task<List<HOME_Appointment_Extended>> GetAppointment_Extended(Guid HOME_Appointment_ID);
        public Task<List<HOME_Appointment_Theme>> GetAppointment_Themes(Guid HOME_Appointment_ID);
        public Task<List<AUTH_Authority_Theme>> GetAuthority_Theme(Guid AUTH_Authority_ID);
        public Task<HOME_Article?> GetArticle(Guid ID);
        public Task<V_HOME_Article?> GetVArticle(Guid ID, Guid LANG_Language_ID);
        public V_HOME_Article? GetLatestArticle(Guid LANG_Language_ID);
        public Task<List<HOME_Article_Extended>> GetArticle_Extended(Guid HOME_Article_ID);
        public Task<List<HOME_Article_Theme>> GetArticle_Themes(Guid HOME_Article_ID);
        public Task<List<HOME_Article_Document>> GetArticle_Documents(Guid HOME_Article_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByArticle(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Article_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByVenue(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Venue_ID);
        public Task<List<V_HOME_Article_Type>> GetArticle_Types(Guid LANG_Language_ID);
        public List<V_HOME_Article_Type> GetArticle_TypesSync(Guid LANG_Language_ID);
        public Task<HOME_Association?> GetAssociation(Guid ID);
        public Task<List<HOME_Association_Extended>> GetAssociation_Extended(Guid HOME_Association_ID);
        public Task<HOME_Document?> GetDocument(Guid ID);
        public Task<V_HOME_Document?> GetVDocument(Guid ID, Guid LANG_Language_ID);
        public Task<List<HOME_Document_Data>?> GetDocumentData(Guid HOME_Document_ID);
        public Task<HOME_Document_Data?> GetDocumentDataByLanguage(Guid HOME_Document_ID, Guid LANG_Language_ID);
        public Task<List<HOME_Document_Document_Type>> GetDocument_Document_Types(Guid HOME_Document_ID);
        public Task<List<HOME_Document_Authority>> GetDocument_Authorities(Guid HOME_Document_ID);
        public Task<List<V_HOME_Authority>> GetDocument_Authorities(Guid HOME_Document_ID, Guid LANG_Language_ID);
        public Task<List<HOME_Document_Extended>> GetDocument_Extended(Guid HOME_Document_ID);
        public Task<List<HOME_Document_Theme>> GetDocument_Themes(Guid HOME_Document_ID);
        public Task<HOME_Municipal_Newsletter?> GetMunicipal_Newsletter(Guid ID);
        public Task<V_HOME_Municipal_Newsletter?> GetVMunicipal_Newsletter(Guid ID, Guid LANG_Language_ID);
        public Task<List<HOME_Municipal_Newsletter_Extended>> GetMunicipal_Newsletter_Extended(Guid HOME_Municipal_Newsletter_ID);
        public Task<HOME_Municipality?> GetMunicipality(Guid ID);
        public Task<HOME_Municipality?> GetMunicipalityByAuthMunicipality(Guid AUTH_Municipality_ID);
        public Task<V_HOME_Municipality?> GetMunicipality(Guid ID, Guid LANG_Language_ID);
        public Task<List<HOME_Municipality_Extended>> GetMunicipality_Extended(Guid HOME_Municipality_ID);
        public Task<MAIN_Detail?> GetMaintenanceDetail(Guid AUTH_Municipality_ID);
        public Task<V_MAIN_Detail?> GetVMaintenanceDetail(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<MAIN_Detail_Extended>> GetMaintenanceDetail_Extended(Guid MAIN_Detail_ID);
        public Task<List<MAIN_Theme>> GetMaintenance_Themes(Guid AUTH_Municipality_ID);
        public Task<MAIN_Theme?> SetMaintenance_Themes(MAIN_Theme Data);
        public Task<bool> RemoveMaintenance_Themes(MAIN_Theme Data);
        public Task<MAIN_Detail?> SetMaintenanceDetail(MAIN_Detail Data);
        public Task<MAIN_Detail_Extended?> SetMaintenanceDetailExtended(MAIN_Detail_Extended Data);
        public Task<HOME_Organisation?> GetOrganisation(Guid ID);
        public Task<List<V_HOME_Person>> GetPeopleByOrganisation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Organisation_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByOrganisation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Organisation_ID);
        public Task<List<V_HOME_Theme>> GetThemesByLocation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Location_ID);
        public Task<List<V_HOME_Person>> GetPeopleByLocation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Location_ID);
        public Task<List<V_HOME_Person>> GetPeopleByFormDefinition(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid FORM_Definition_ID);
        public Task<List<V_HOME_Document>> GetDocumentsByLocation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Location_ID);
        public Task<List<V_HOME_Theme>> GetThemesByOrganisation(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Organisation_ID);
        public Task<List<V_HOME_Theme>> GetThemesByPNRR(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_PNRR_ID);
        public Task<List<V_HOME_Theme>> GetThemesByAppointment(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Appointment_ID);
        public Task<V_HOME_Organisation?> GetVOrganisation(Guid ID, Guid LANG_Languages_ID);
        public Task<List<HOME_Organisation_Extended>> GetOrganisation_Extended(Guid HOME_Organisation_ID);
        public Task<List<HOME_Organisation_Person>> GetOrganisation_People(Guid HOME_Organisation_ID);
        public Task<List<HOME_Organisation_Theme>> GetOrganisation_Themes(Guid HOME_Organisation_ID);
        public Task<HOME_Organisation_Type?> GetOrganisationType(Guid ID);
        public Task<List<HOME_Organisation_Type_Extended>> GetOrganisation_Type_Extended(Guid HOME_Organisation_Type_ID);
        public Task<HOME_Person?> GetPerson(Guid ID);
        public Task<List<HOME_Person_Extended>> GetPerson_Extended(Guid HOME_Person_ID);
        public Task<List<HOME_Person_Authority>> GetPerson_Authorities(Guid HOME_Person_ID);
        public Task<List<HOME_Person_Document>> GetPerson_Documents(Guid HOME_Person_ID);
        public Task<HOME_Questionnaire?> GetQuestionnaire(Guid ID);
        public Task<HOME_Theme?> GetTheme(Guid ID);
        public Task<V_HOME_Theme?> GetVTheme(Guid ID, Guid LANG_Language_ID);
        public Task<V_HOME_Person?> GetVPerson(Guid ID, Guid LANG_Language_ID);
        public Task<V_HOME_Authority?> GetVAuthority(Guid ID, Guid LANG_Language_ID);
        public Task<List<HOME_Theme_Extended>> GetTheme_Extended(Guid HOME_Theme_ID);
        public Task<HOME_Theme_Type?> GetThemeType(Guid ID);
        public Task<List<HOME_Theme_Type_Extended>> GetTheme_Type_Extended(Guid HOME_Theme_Type_ID);
        public Task<HOME_Venue?> GetVenue(Guid ID);
        public Task<V_HOME_Venue?> GetVVenue(Guid ID, Guid LANG_Language_ID);
        public Task<List<HOME_Venue_Extended>> GetVenue_Extended(Guid HOME_Venue_ID);
        public Task<List<HOME_Venue_Document>> GetVenue_Documents(Guid HOME_Venue_ID);
        public Task<HOME_Venue_Type?> GetVenueType(Guid ID);
        public Task<List<HOME_Venue_Type_Extended>> GetVenue_Type_Extended(Guid HOME_Venue_Type_ID);
        public Task<List<HOME_Venue_Person>> GetVenue_People(Guid HOME_Venue_ID);
        public Task<List<HOME_Venue_Theme>> GetVenue_Themes(Guid HOME_Venue_ID);
        public Task<HOME_Appointment?> SetAppointment(HOME_Appointment Data);
        public Task<HOME_Appointment_Dates?> SetAppointmentDate(HOME_Appointment_Dates Data);
        public Task<HOME_Appointment_Extended?> SetAppointmentExtended(HOME_Appointment_Extended Data);
        public Task<HOME_Appointment_Theme?> SetAppointmentTheme(HOME_Appointment_Theme Data);
        public Task<HOME_Article?> SetArticle(HOME_Article Data);
        public Task<HOME_Article_Extended?> SetArticleExtended(HOME_Article_Extended Data);
        public Task<HOME_Article_Theme?> SetArticleTheme(HOME_Article_Theme Data);
        public Task<HOME_Association?> SetAssociation(HOME_Association Data);
        public Task<HOME_Association_Extended?> SetAssociationExtended(HOME_Association_Extended Data);
        public Task<HOME_Association_Person_Extended?> SetAssociationPersonExtended(HOME_Association_Person_Extended Data);
        public Task<HOME_Document?> SetDocument(HOME_Document Data);
        public Task<HOME_Document_Data?> SetDocumentData(HOME_Document_Data Data);
        public Task<HOME_Document_Document_Type?> SetDocumentDocumentType(HOME_Document_Document_Type Data);
        public Task<HOME_Document_Extended?> SetDocumentExtended(HOME_Document_Extended Data);
        public Task<HOME_Document_Format?> SetDocumentFormat(HOME_Document_Format Data);
        public Task<HOME_Document_License?> SetDocumentLicense(HOME_Document_License Data);
        public Task<HOME_Document_Theme?> SetDocumentTheme(HOME_Document_Theme Data);
        public Task<HOME_Document_Type?> SetDocumentType(HOME_Document_Type Data);
        public Task<HOME_Municipal_Newsletter?> SetMunicipalNewsletter(HOME_Municipal_Newsletter Data);
        public Task<HOME_Municipal_Newsletter_Extended?> SetMunicipalNewsletterExtended(HOME_Municipal_Newsletter_Extended Data);
        public Task<HOME_Municipality?> SetMunicipality(HOME_Municipality Data);
        public Task<HOME_Municipality_Extended?> SetMunicipalityExtended(HOME_Municipality_Extended Data);
        public Task<HOME_Organisation?> SetOrganisation(HOME_Organisation Data);
        public Task<HOME_Organisation_Extended?> SetOrganisationExtended(HOME_Organisation_Extended Data);
        public Task<HOME_Organisation_Person?> SetOrganisationPerson(HOME_Organisation_Person Data);
        public Task<HOME_Organisation_Theme?> SetOrganisationTheme(HOME_Organisation_Theme Data);
        public Task<HOME_Organisation_Type?> SetOrganisationType(HOME_Organisation_Type Data);
        public Task<HOME_Organisation_Type_Extended?> SetOrganisationTypeExtended(HOME_Organisation_Type_Extended Data);
        public Task<HOME_Venue_Person?> SetVenuePerson(HOME_Venue_Person Data);
        public Task<HOME_Venue_Theme?> SetVenueTheme(HOME_Venue_Theme Data);
        public Task<HOME_Person?> SetPerson(HOME_Person Data);
        public Task<HOME_Person_Extended?> SetPersonExtended(HOME_Person_Extended Data);
        public Task<HOME_Person_Authority?> SetPersonAuthority(HOME_Person_Authority Data);
        public Task<HOME_Questionnaire?> SetQuestinnaire(HOME_Questionnaire Data);
        public Task<HOME_Theme?> SetTheme(HOME_Theme Data);
        public Task<HOME_Theme_Extended?> SetThemeExtended(HOME_Theme_Extended Data);
        public Task<HOME_Theme_Type?> SetThemeType(HOME_Theme_Type Data);
        public Task<HOME_Theme_Type_Extended?> SetThemeTypeExtended(HOME_Theme_Type_Extended Data);
        public Task<HOME_Venue?> SetVenue(HOME_Venue Data);
        public Task<HOME_Venue_Document?> SetVenueDocument(HOME_Venue_Document Data);
        public Task<HOME_Venue_Extended?> SetVenueExtended(HOME_Venue_Extended Data);
        public Task<HOME_Venue_Type?> SetVenueType(HOME_Venue_Type Data);
        public Task<HOME_Venue_Type_Extended?> SetVenueTypeExtended(HOME_Venue_Type_Extended Data);
        public Task<HOME_Document_Authority?> SetDocumentAuthority(HOME_Document_Authority Data);
        public Task<HOME_Article_Document?> SetArticleDocument(HOME_Article_Document Data);
        public Task<bool> RemoveAppointment(HOME_Appointment Data);
        public Task<bool> RemoveAppointment(Guid ID);
        public Task<bool> RemoveAppointmentDate(HOME_Appointment_Dates Data);
        public Task<bool> RemoveAppointmentDate(Guid ID);
        public Task<bool> RemoveAppointmentExtended(HOME_Appointment_Extended Data);
        public Task<bool> RemoveAppointmentTheme(HOME_Appointment_Theme Data);
        public Task<bool> RemoveArticle(HOME_Article Data);
        public Task<bool> RemoveArticle(Guid ID);
        public Task<bool> RemoveArticleExtended(HOME_Article_Extended Data);
        public Task<bool> RemoveArticleTheme(HOME_Article_Theme Data);
        public Task<bool> RemoveAssociation(HOME_Association Data);
        public Task<bool> RemoveAssociation(Guid ID);
        public Task<bool> RemoveAssociationExtended(HOME_Association_Extended Data);
        public Task<bool> RemoveDocument(HOME_Document Data);
        public Task<bool> RemoveDocumentData(HOME_Document_Data Data);
        public Task<bool> RemoveDocumentData(Guid ID);
        public Task<bool> RemoveDocument(Guid ID);
        public Task<bool> RemoveDocumentExtended(HOME_Document_Extended Data);
        public Task<bool> RemoveDocumentTheme(HOME_Document_Theme Data);
        public Task<bool> RemoveDocumentTheme(Guid ID);
        public Task<bool> RemoveDocumentDocumentType(HOME_Document_Document_Type Data);
        public Task<bool> RemoveMunicipalNewsletter(HOME_Municipal_Newsletter Data);
        public Task<bool> RemoveMunicipalNewsletter(Guid ID);
        public Task<bool> RemoveMunicipalNewsletterExtended(HOME_Municipal_Newsletter_Extended Data);
        public Task<bool> RemoveMunicipality(HOME_Municipality Data);
        public Task<bool> RemoveMunicipalityExtended(HOME_Municipality_Extended Data);
        public Task<bool> RemoveOrganisation(HOME_Organisation Data);
        public Task<bool> RemoveOrganisationExtended(HOME_Organisation_Extended Data);
        public Task<bool> RemoveOrganisationTheme(HOME_Organisation_Theme Data);
        public Task<bool> RemoveOrganisationType(HOME_Organisation_Type Data);
        public Task<bool> RemoveOrganisationType(Guid ID);
        public Task<bool> RemoveOrganisationTypeExtended(HOME_Organisation_Type_Extended Data);
        public Task<bool> RemoveOrganisationPerson(HOME_Organisation_Person Data);
        public Task<bool> RemovePerson(HOME_Person Data);
        public Task<bool> RemovePerson(Guid ID);
        public Task<bool> RemovePersonExtended(HOME_Person_Extended Data);
        public Task<bool> RemoveQuestionnaire(HOME_Questionnaire Data);
        public Task<bool> RemoveTheme(HOME_Theme Data);
        public Task<bool> RemoveTheme(Guid ID);
        public Task<bool> RemoveThemeExtended(HOME_Theme_Extended Data);
        public Task<bool> RemoveThemeType(HOME_Theme_Type Data);
        public Task<bool> RemoveThemeTypeExtended(HOME_Theme_Type_Extended Data);
        public Task<bool> RemoveVenue(HOME_Venue Data);
        public Task<bool> RemoveVenue(Guid ID);
        public Task<bool> RemoveVenueDocument(HOME_Venue_Document Data);
        public Task<bool> RemoveVenueExtended(HOME_Venue_Extended Data);
        public Task<bool> RemoveVenueType(HOME_Venue_Type Data);
        public Task<bool> RemoveVenueType(Guid ID);
        public Task<bool> RemoveVenueTypeExtended(HOME_Venue_Type_Extended Data);
        public Task<bool> RemoveVenuePerson(HOME_Venue_Person Data);
        public Task<bool> RemoveVenuePerson(Guid ID);
        public Task<bool> RemoveVenueTheme(HOME_Venue_Theme Data);
        public Task<bool> RemoveVenueTheme(Guid ID);
        public Task<bool> RemovePersonAuthority(HOME_Person_Authority Data);
        public Task<bool> RemovePersonAuthority(Guid ID);
        public Task<bool> RemoveDocumentAuthority(HOME_Document_Authority Data);
        public Task<bool> RemoveDocumentAuthority(Guid ID);
        public Task<bool> RemoveArticleDocument(HOME_Article_Document Data);
        public Task<bool> RemoveArticleDocument(Guid ID);
        public Task<bool> CheckThemeHighlight(Guid HOME_Theme_ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckArticleHighlight(Guid HOME_Article_ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckAppointmentHighlight(Guid HOME_Appointment_ID, Guid HOME_Appointment_Type_ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckAssociationHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckAuthorityHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckDocumentsHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckOrganisationHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckPersonHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckVenueHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<bool> CheckLocatinHighlight(Guid ID, Guid AUTH_Municipality_ID);
        public Task<List<V_HOME_Appointment_Type>> GetAppointment_Type(Guid LANG_Language_ID);
        public Task<List<V_HOME_Appointment_Kategorie>> GetAppointment_Kategories(Guid LANG_Language_ID);
        public List<V_HOME_Thematic_Sites> GetThematicsites(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Thematic_Sites>> GetThematicsitesByType(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Thematic_Sites_Type_ID);
        public List<V_HOME_Thematic_Sites> GetThematicsitesByTypeSync(Guid AUTH_Municipality_ID, Guid LANG_Language_ID, Guid HOME_Thematic_Sites_Type_ID);
        public Task<List<V_HOME_Thematic_Sites_Type>> GetThematicsitesTypes(Guid LANG_Language_ID);
        public Task<HOME_Thematic_Sites?> GetThematicsite(Guid ID);
        public Task<V_HOME_Thematic_Sites?> GetVThematicsite(Guid ID, Guid LANG_Language_ID);
        public Task<bool> RemoveThematicsites(HOME_Thematic_Sites Data);
        public Task<bool> RemoveThematicsites(Guid ID);
        public Task<HOME_Thematic_Sites?> SetThematicsites(HOME_Thematic_Sites Data);
        public Task<bool> RemoveAuthorityTheme(AUTH_Authority_Theme Data);
        public Task<AUTH_Authority_Theme?> SetAuthorityTheme(AUTH_Authority_Theme Data);
        public Task<HOME_Thematic_Sites_Extended?> SetThematicsite_Extended(HOME_Thematic_Sites_Extended Data);
        public Task<HOME_Thematic_Sites_Document?> SetThematicsite_Document(HOME_Thematic_Sites_Document Data);
        public Task<bool> RemoveThematicsite_Document(Guid ID);
        public Task<List<HOME_Thematic_Sites_Extended>> GetThematicsite_Extended(Guid HOME_Thematicsites_ID);
        public Task<List<HOME_Thematic_Sites_Document>> GetThematicsite_Documents(Guid HOME_Thematicsites_ID);
        public Task<bool> RemovePersonDocument(HOME_Person_Document Data);
        public Task<HOME_Person_Document?> SetPersonDocument(HOME_Person_Document Data);
        public Task<bool> RemoveOrganisationDocument(HOME_Organisation_Document Data);
        public Task<HOME_Organisation_Document?> SetOrganisationDocument(HOME_Organisation_Document Data);
        public Task<List<HOME_Organisation_Document>> GetOrganisation_Documents(Guid HOME_Organisation_ID);
        public Task<bool> RemoveAssociationPerson(HOME_Association_Person Data);
        public Task<HOME_Association_Person?> SetAssociationPerson(HOME_Association_Person Data);
        public Task<List<HOME_Association_Person>> GetAssociation_People(Guid HOME_Association_ID);
        public Task<List<V_HOME_Organisation_Person>> GetOrganisationVPeople(Guid HOME_Organisation_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Association_Person>> GetAssociationVPeople(Guid HOME_Association_ID, Guid LANG_Language_ID);
        public Task<bool> RemoveAssociationTheme(HOME_Association_Theme Data);
        public Task<HOME_Association_Theme?> SetAssociationTheme(HOME_Association_Theme Data);
        public Task<List<HOME_Association_Theme>> GetAssociation_Themes(Guid HOME_Association_ID);
        public Task<bool> RemoveAssociationDocument(HOME_Association_Document Data);
        public Task<HOME_Association_Document?> SetAssociationDocument(HOME_Association_Document Data);
        public Task<List<HOME_Association_Document>> GetAssociation_Documents(Guid HOME_Association_ID);
        public Task<List<V_HOME_Association_Type>> GetAssociation_Type(Guid LANG_Language_ID);
        public Task<HOME_Location_Document?> SetLocationDocument(HOME_Location_Document Data);
        public Task<List<HOME_Location_Document>> GetLocation_Documents(Guid HOME_Location_ID);
        public Task<bool> RemoveLocationDocument(HOME_Location_Document Data);
        public Task<HOME_Location_Theme?> SetLocationTheme(HOME_Location_Theme Data);
        public Task<List<HOME_Location_Theme>> GetLocation_Themes(Guid HOME_Location_ID);
        public Task<bool> RemoveLocationTheme(HOME_Location_Theme Data);
        public Task<HOME_Location_Person?> SetLocationPerson(HOME_Location_Person Data);
        public Task<List<HOME_Location_Person>> GetLocation_People(Guid HOME_Location_ID);
        public Task<bool> RemoveLocationPerson(HOME_Location_Person Data);
        public Task<HOME_Location_Extended?> SetLocationExtended(HOME_Location_Extended Data);
        public Task<List<HOME_Location_Extended>> GetLocation_Extended(Guid HOME_Location_ID);
        public Task<V_HOME_Location?> GetVLocation(Guid HOME_Location_ID, Guid LANG_Language_ID);
        public Task<HOME_Location?> GetLocation(Guid HOME_Location_ID);
        public Task<HOME_Location?> SetLocation(HOME_Location Data);
        public Task<bool> RemoveLocation(HOME_Location Data);
        public Task<bool> RemoveLocation(Guid ID);
        public Task<bool> RemoveFaq(Guid ID);
        public Task<HOME_Faq?> SetFaq(HOME_Faq Data);
        public Task<HOME_Faq?> GetFaq(Guid ID);
        public Task<List<HOME_Faq_Extended>> GetFaq_Extended(Guid HOME_Faq_ID);
        public Task<HOME_Faq_Extended?> SetFaq_Extended(HOME_Faq_Extended Data);
        public Task<List<V_HOME_Location_Type>> GetLocation_Type(Guid LANG_Language_ID);
        public Task<List<V_HOME_Location>> GetLocations(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<HOME_Assistance?> SetAssistance(HOME_Assistance Data);
        public Task<HOME_Assistance?> GetAssistance(Guid ID);
        public Task<List<HOME_Assistance>> GetAssistances(Guid AUTH_Municipality_ID, bool Completed = false);
        public Task<HOME_Request?> GetRequest(Guid AUTH_Municipality_ID, Guid AUTH_Authority_ID, DateTime DateFrom);
        public Task<HOME_Request?> GetRequest(Guid ID);
        public Task<HOME_Request?> SetRequest(HOME_Request Data);
        public Task<HOME_Person_Request?> GetPersonRequest(Guid AUTH_Municipality_ID, Guid HOME_Person_ID, DateTime DateFrom);
        public Task<HOME_Person_Request?> GetPersonRequest(Guid ID);
        public Task<List<V_HOME_Person_Request>> GetPersonUserRequest(Guid AUTH_Users_ID);
        public Task<List<V_HOME_Request>> GetUserRequest(Guid AUTH_Users_ID);
        public Task<HOME_Person_Request?> SetPersonRequest(HOME_Person_Request Data);
        public Task<List<V_HOME_Person_Request>> GetPersonRequests(Guid AUTH_Municipality_ID);
        public Task<List<V_HOME_Request>> GetRequests(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<bool> RemoveRequest(Guid ID);
        public Task<bool> RemovePersonRequest(Guid ID);
        public Task<List<V_HOME_Theme>> GetThemesByMaintenance(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<HOME_Accessibility?> GetAccessibility(Guid AUTH_Municipality_ID);
        public Task<HOME_Accessibility?> SetAccessibility(HOME_Accessibility Data);
        public Task<V_HOME_Accessibility?> GetVAccessibility(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<List<HOME_Accessibility_Extended>> GetAccessibilityExtended(Guid HOME_Accessibility_ID);
        public Task<HOME_Accessibility_Extended?> SetAccessibilityExtended(HOME_Accessibility_Extended Data);
        public Task<List<V_HOME_Association_Person_Type>> GetAssosiactionPeopleTypes(Guid LANG_Language_ID);
        public Task<List<V_HOME_Organisation_Person_Type>> GetOrganisationPeopleTypes(Guid LANG_Language_ID);
        public Task<List<HOME_Municipality_Images>> GetMunicipality_Images(Guid AUTH_Municipality_ID);
        public Task<HOME_Municipality_Images?> SetMunicipality_Images(HOME_Municipality_Images Data);
        public Task<bool> RemoveMunicipality_Images(HOME_Municipality_Images Data);
        public Task<bool> RemoveMunicipality_Images(Guid ID);
        public Task<List<HOME_Person_Dates_Timeslots>> GetPersonTimes(Guid HOME_Person_ID);
        public Task<List<HOME_Person_Office_Hours>> GetPersonOfficeHours(Guid HOME_Person_ID);
        public Task<List<HOME_Person_Dates_Closed>> GetPersonClosedDates(Guid HOME_Person_ID);
        public Task<bool> RemovePersonTimes(HOME_Person_Dates_Timeslots Data);
        public Task<bool> RemovePersonTimes(Guid ID);
        public Task<bool> RemovePersonOfficeHours(HOME_Person_Office_Hours Data);
        public Task<bool> RemovePersonOfficeHours(Guid ID);
        public Task<bool> RemovePersonClosedDates(HOME_Person_Dates_Closed Data);
        public Task<bool> RemovePersonClosedDates(Guid ID);
        public Task<HOME_Person_Dates_Timeslots?> SetPersonTimes(HOME_Person_Dates_Timeslots Data);
        public Task<HOME_Person_Office_Hours?> SetPersonOfficeHours(HOME_Person_Office_Hours Data);
        public Task<HOME_Person_Dates_Closed?> SetPersonClosedDates(HOME_Person_Dates_Closed Data);
        public Task<V_HOME_Municipal_Newsletter_Type?> GetNewsletter_Type(Guid HOME_Municipal_Newsletter_Type_ID, Guid LANG_Language_ID);
        public Task<List<V_HOME_Municipal_Newsletter_Type>> GetNewsletter_Types(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<HOME_Municipal_Newsletter_Type?> GetNewsletterType(Guid HOME_Municipal_Newsletter_Type_ID);
        public Task<List<HOME_Municipal_Newsletter_Type_Extended>> GetNewsletterType_Extended(Guid HOME_Municipal_Newsletter_Type_ID);
        public Task<HOME_Municipal_Newsletter_Type?> SetNewsletterType(HOME_Municipal_Newsletter_Type Data);
        public Task<HOME_Municipal_Newsletter_Type_Extended?> SetNewsletterTypeExtended(HOME_Municipal_Newsletter_Type_Extended Data);
        public Task<bool> RemoveNewsletterType(Guid ID);
        public Task<List<HOME_Association_Person_Extended>> GetAssociationsPersonExtended(Guid HOME_Association_Person_ID);
        public Task<List<V_HOME_Impressum>> GetImpressum(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<HOME_Impressum?> GetImpressum(Guid ID);
        public Task<HOME_Impressum?> SetImpressum(HOME_Impressum Data);
        public Task<List<HOME_Impressum_Extended>> GetImpressum_Extended(Guid HOME_Impressum_ID);
        public Task<HOME_Impressum_Extended?> SetImpressum_Extended(HOME_Impressum_Extended Data);
        public Task<bool> RemoveImpressum(Guid ID);
        public Task<List<V_HOME_Privacy>> GetPrivacy(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<HOME_Privacy?> GetPrivacy(Guid ID);
        public Task<HOME_Privacy?> SetPrivacy(HOME_Privacy Data);
        public Task<List<HOME_Privacy_Extended>> GetPrivacy_Extended(Guid HOME_Privacy_ID);
        public Task<List<HOME_Privacy_Document>> GetPrivacy_Document(Guid HOME_Privacy_ID);
        public List<HOME_Privacy_Document> GetPrivacy_DocumentSync(Guid HOME_Privacy_ID);
        public Task<HOME_Privacy_Extended?> SetPrivacy_Extended(HOME_Privacy_Extended Data);
        public Task<HOME_Privacy_Document?> SetPrivacy_Document(HOME_Privacy_Document Data);
        public Task<bool> RemovePrivacy(Guid ID);
        public Task<bool> RemovePrivacy_Document(Guid ID);
        public Task<List<V_HOME_PNRR>> GetPNRR(Guid AUTH_Municipality_ID, Guid LANG_Language_ID);
        public Task<V_HOME_PNRR?> GetPNRRSingle(Guid ID, Guid LANG_Language_ID);
        public Task<HOME_PNRR?> GetPNRR(Guid ID);
        public Task<HOME_PNRR?> SetPNRR(HOME_PNRR Data);
        public Task<List<HOME_PNRR_Extended>> GetPNRR_Extended(Guid HOME_PNRR_ID);
        public Task<HOME_PNRR_Extended?> SetPNRR_Extended(HOME_PNRR_Extended Data);
        public Task<bool> RemovePNRR(Guid ID);
        public Task<List<HOME_PNRR_Chapter>> GetPNRRChapterList(Guid HOME_PNRR_ID);
        public Task<List<V_HOME_PNRR_Chapter>> GetPNRRChapterList(Guid HOME_PNRR_ID, Guid LANG_Language_ID);
        public Task<HOME_PNRR_Chapter?> SetPNRRChapter(HOME_PNRR_Chapter Data);
        public Task<HOME_PNRR_Chapter?> GetPNRRChapter(Guid ID);
        public Task<List<HOME_PNRR_Chapter_Extended>> GetPNRRChapter_Extended(Guid HOME_PNRR_Chapter_ID);
        public Task<HOME_PNRR_Chapter_Extended?> SetPNRRChapter_Extended(HOME_PNRR_Chapter_Extended Data);
        public Task<List<V_HOME_PNRR_Chapter_Document>> GetPNRRChapter_Document(Guid HOME_PNRR_Chapter_ID, Guid LANG_Language_ID);
        public Task<HOME_PNRR_Chapter_Document> GetPNRRChapter_Document(Guid ID);
        public List<V_HOME_PNRR_Chapter_Document> GetPNRRChapter_DocumentSync(Guid HOME_PNRR_Chapter_ID, Guid LANG_Language_ID);
        public Task<List<HOME_PNRR_Chapter_Document_Extended>> GetPNRRChapterDocument_Extended(Guid HOME_PNRR_Chapter_Document_ID);
        public Task<HOME_PNRR_Chapter_Document_Extended?> SetPNRRChapterDocument_Extended(HOME_PNRR_Chapter_Document_Extended Data);
        public Task<HOME_PNRR_Chapter_Document?> SetPNRRChapter_Document(HOME_PNRR_Chapter_Document Data);
        public Task<HOME_PNRR_Theme?> SetPNRRTheme(HOME_PNRR_Theme Data);
        public Task<List<HOME_PNRR_Theme>> GetPNRR_Themes(Guid HOME_PNRR_ID);
        public Task<bool> RemovePNRRTheme(HOME_PNRR_Theme Data);
        public Task<bool> RemovePNRRChapter_Document(Guid ID);
        public Task<bool> RemovePNRRChapter(Guid ID);
        public Task<List<V_HOME_PNRR_Type>> GetPNRRTypes(Guid LANG_Language_ID);
    }
}
